<div data-role="header" data-theme="b" data-position="fixed" data-id="main-admin-header" data-tap-toggle="false">
	<div data-role="navbar" id="main-admin-header-navbar">
		<ul>
			<li><a href="#admin_events" data-icon="calendar" data-transition="none">Events</a></li>
			<li><a href="#admin_users" data-icon="user" data-transition="none">Benutzer</a></li>
			<li><a href="#admin_menues" data-icon="bullets" data-transition="none">Menüs</a></li>			
			<li><a href="#order-overview" data-icon="back" data-transition="none">Zurück</a></li>
		</ul>
	</div><!-- /navbar -->
</div><!-- /header -->