<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="header">
        <h2>Event Kopieren</h2>
    </div>
    <fieldset data-role="controlgroup">
        <legend>Name:</legend>
        <input type="text" id="name" value="<%- event.get('Name') %>">
        <label for="admin-event-modify-name"></label>
    </fieldset>

    <fieldset data-role="controlgroup">
        <legend>Datum:</legend>
        <input type="text" id="date" name="date" data-role="datebox" data-options='{"mode":"calbox", "overrideDateFormat": "%d.%m.%Y"}'  value="<% if(!event.isNew()) { print(app.i18n.toDate(event.get('Date'))); } %>">
    </fieldset>

     <fieldset data-role="controlgroup">
        <legend>Eigenschaften kopieren:</legend>
        <input type="checkbox" id="date">
        <label for="date">Menüs</label>
        <input type="checkbox" id="table">
        <label for="table">Tische</label>
        <input type="checkbox" id="distribution">
        <label for="distribution">Ausgabestellen</label>
        <input type="checkbox" id="printer">
        <label for="printer">Drucker</label>
        <input type="checkbox" id="user">
        <label for="user">Berechtigungen</label>
    </fieldset>

    <div class="ui-field-contain">
        <a id="finished-btn" class="ui-btn ui-btn-inline">Kopieren</a>
    </div>
</div>