<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="header">
        <h2><%= t.eventCopy %></h2>
    </div>
    <fieldset data-role="controlgroup">
        <legend><%= t.name %>:</legend>
        <input type="text" id="name" value="<%- event.get('Name') %>">
        <label for="admin-event-modify-name"></label>
    </fieldset>

    <fieldset data-role="controlgroup">
        <legend><%= t.date %>:</legend>
        <input type="text" id="date" name="date" data-role="datebox" data-options='{"mode":"calbox", "overrideDateFormat": "%d.%m.%Y"}'  value="<% if(!event.isNew()) { print(app.i18n.toDate(event.get('Date'))); } %>">
    </fieldset>

     <fieldset data-role="controlgroup">
        <legend><%= t.copySettings %>:</legend>
        <input type="checkbox" id="menu">
        <label for="menu"><%= t.menu %></label>
        <input type="checkbox" id="table">
        <label for="table"><%= t.table %></label>
        <input type="checkbox" id="distribution">
        <label for="distribution"><%= t.distribution %></label>
        <input type="checkbox" id="printer">
        <label for="printer"><%= t.printer %></label>
        <input type="checkbox" id="permission">
        <label for="permission"><%= t.permission %></label>
    </fieldset>

    <div class="ui-field-contain">
        <a id="finished-btn" class="ui-btn ui-btn-inline"><%= t.copy %></a>
    </div>
</div>