<div data-role="content">
    <a class="add-btn ui-btn ui-icon-plus ui-mini ui-btn-icon-left"><%= t.add %></a>
    <table data-role="table" id="table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.name %></th>
                <th><%= t.date %></th>
                <th><%= t.active %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody>
            <% events.each(function(event){ %>
                <tr>
                    <th><%- event.get('Name') %></th>
                    <td><%- app.i18n.toDate(event.get('Date')) %></td>
                    <td><% if(event.get('Active') == 1) { print(t.yes); } else { print(t.no); } %></td>
                    <td>
                        <a data-event-cid="<%- event.cid %>" class="copy-btn ui-btn ui-icon-files-o ui-mini ui-btn-icon-left"><%= t.copy %></a>
                        <a data-event-cid="<%- event.cid %>" class="edit-settings-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left"><%= t.editSettings %></a>
                        <a data-event-cid="<%- event.cid %>" class="edit-details-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left"><%= t.editDetails %></a>
                        <a data-event-cid="<%- event.cid %>" class="active-btn ui-btn ui-icon-star ui-mini ui-btn-icon-left"><%= t.setActive %></a>
                    </td>
                </tr>
            <% }); %>
        </tbody>
    </table>
</div>
<div data-role="popup" id="activate-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1><%= t.eventActivate %></h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.eventActivateVerifyText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='activate-dialog-finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>