<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="header">
        <h2><% if(user.isNew()) { print('Neuer Benutzer'); } else { print('Benutzer Bearbeiten'); } %></h2>
    </div>
    <form id='form'>
        <fieldset data-role="controlgroup">
            <legend>Benutzername:</legend>
            <input type="text" id="username" name='username' value="<%- user.get('Username') %>">
            <label for="username"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Password und Passwort wiederhollen:</legend>
            <input type="password" id="password" name="password">
            <label for="password"></label>
            <input type="password" id="password2" name="password2">
            <label for="password2"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Vorname:</legend>
            <input type="text" id="firstname" name='firstname' value="<%- user.get('Firstname') %>">
            <label for="firstname"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Nachname:</legend>
            <input type="text" id="lastname" name='lastname' value="<%- user.get('Lastname') %>">
            <label for="lastname"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Telefonnummer:</legend>
            <input type="text" id="phonenumber" name='phonenumber' value="<%- user.get('Phonenumber') %>">
            <label for="phonenumber"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Optionen:</legend>
            <input type="checkbox" name="isAdmin" id="isAdmin" <% if(user.get('IsAdmin')) { print('checked="checked"'); } %>>
            <label for="isAdmin">Administrator</label>
            <input type="checkbox" name="active" id="active"  <% if(user.get('Active')) { print('checked="checked"'); } %>>
            <label for="active">Aktiv</label>
        </fieldset>

        <div class="ui-field-contain">
            <a id="save-btn" class="ui-btn ui-btn-inline">Speichern</a>
        </div>
    </form>
</div>