<div data-role="content">
    <a id="add-btn" class="ui-btn ui-icon-plus ui-mini ui-btn-icon-left"><%= t.add %></a>
    <table data-role="table" id="table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.username %></th>
                <th><%= t.name %></th>
                <th><%= t.active %></th>
                <th><%= t.admin %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody id="users-list">
        </tbody>
    </table>
</div>
<div data-role="popup" id="delete-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1><%= t.userDelete %></h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.userDeleteVerifyText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='delete-dialog-finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>