<div data-role="content">
    <div data-role="header">
        <h2><% if(isNew) { print(t.newUser); } else { print(t.editUser); } %></h2>
    </div>
    <form id='form'>
        <fieldset data-role="controlgroup">
            <legend><%= t.username %>:</legend>
            <input type="text" id="username" name='username'>
            <label for="username"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend><%= t.passwords %>:</legend>
            <input type="password" id="password" name="password">
            <label for="password"></label>
            <input type="password" id="password2" name="password2">
            <label for="password2"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend><%= t.firstname %>:</legend>
            <input type="text" id="firstname" name='firstname'>
            <label for="firstname"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend><%= t.lastname %>:</legend>
            <input type="text" id="lastname" name='lastname'>
            <label for="lastname"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend><%= t.phonenumber %>:</legend>
            <input type="text" id="phonenumber" name='phonenumber'>
            <label for="phonenumber"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend><%= t.options %>:</legend>
            <input type="checkbox" name="isAdmin" id="isAdmin">
            <label for="isAdmin"><%= t.admin %></label>
        </fieldset>

        <div class="ui-field-contain">
            <a id="save-btn" class="ui-btn ui-btn-inline"><%= t.save %></a>
        </div>
    </form>
</div>