<div data-role="header" data-theme="b" data-position="fixed" data-id="main-admin-header" data-tap-toggle="false">
    <div data-role="navbar" id="main-admin-header-navbar">
        <ul>
            <li><a href="#admin/event" class="admin-header-link<% if(activeButton == 'event') { %> ui-btn-active<% } %>" data-icon="calendar">Events</a></li>
            <li><a href="#admin/user" class="admin-header-link<% if(activeButton == 'user') { %> ui-btn-active<% } %>" data-icon="user" >Benutzer</a></li>
            <li><a href="#admin/menu" class="admin-header-link<% if(activeButton == 'menu') { %> ui-btn-active<% } %>" data-icon="bullets">Menüs</a></li>
            <li><a href="#" class="admin-header-link" data-icon="back" data-transition="none">Zurück</a></li>
        </ul>
    </div>
</div>