<div class="ui-btn-left">
    <a href="#" data-role="button" id='menu' data-icon="bullets" data-iconpos="notext" class="side-menu-open" style="margin-top: .2em;"></a>
</div>
<h1 data-user="fullname"><%- name %></h1>
<div class="ui-btn-right">
    <a href="#messages-dialog" data-role="button" id='messages' data-icon="comment" class='navbar-header-messages-counter'><%- unreadedMessages %></a>
    <a href="#options-dialog" data-role="button" id='options' data-icon="gear" data-iconpos="notext"></a>
</div>