<div data-role="header" data-theme="b" data-position="fixed" data-id="main-header" data-tap-toggle="false">
    <h1 data-user="fullname"><%- name %></h1>
    <div class="ui-btn-right">
        <a href="#messages-dialog" data-role="button" id='navbar-header-messages' data-icon="comment" class='navbar-header-messages-counter'><%- unreadedMessages %></a>
        <a href="#options-dialog" data-role="button" id='navbar-header-options' data-icon="gear" data-iconpos="notext"></a>
    </div>
    <div data-role="navbar" id="main-header-navbar">
        <ul>
            <% if(rights & USER_ROLE_WAITRESS) { %>
                <li><a href="#order-new" class="header-link<% if(activeButton == 'order-new') { %> ui-btn-active<% } %>" data-icon="plus" data-transition="none">Neu</a></li>
                <li><a href="#order-overview" class="header-link<% if(activeButton == 'order-overview') { %> ui-btn-active<% } %>"  data-icon="grid" data-transition="none">Bestellungen</a></li>
            <% } %>
            <% if(rights & USER_ROLE_DISTRIBUTION) { %>
                <li><a href="#distribution" class="header-link <% if(activeButton == 'distribution') { %> ui-btn-active<% } %>"  data-icon="star" data-transition="none">Ausgabe</a></li>
            <% } %>
            <% if(rights & USER_ROLE_MANAGER) { %>
                <li><a href="#manager" class="header-link <% if(activeButton == 'manager') { %> ui-btn-active<% } %>"  data-icon="eye" data-transition="none">Manager</a></li>
            <% } %>
        </ul>
    </div>
</div>