<div data-role="panel" data-display="overlay" id="side-menu" data-position="left">
        <ul data-role="listview" data-icon="false">
            <li data-role="list-divider">Menü</li>
            <li><a id="new">Neu</a></li>
            <li><a>Bestellungen</a></li>
            <li><a>Rechnungen</a></li>
            <li><a>Ausgabe</a></li>
            <li><a>Manager</a></li>
        </ul>
</div>