<div data-role="navbar">
    <ul>
        <li><a href="<%- link %>" class="link<% if(activeButton == 'oberview') { %> ui-btn-active<% } %>" data-icon="info">Übersicht</a></li>
        <li><a href="<%- link %>/menu" class="link<% if(activeButton == 'menu') { %> ui-btn-active<% } %>" data-icon="cutlery">Menüs</a></li>
        <li><a href="<%- link %>/size" class="link<% if(activeButton == 'size') { %> ui-btn-active<% } %>" data-icon="cutlery">Größen</a></li>
        <li><a href="<%- link %>/user" class="link<% if(activeButton == 'user') { %> ui-btn-active<% } %>" data-icon="user">Berechtigungen</a></li>
        <li><a href="<%- link %>/distribution" class="link<% if(activeButton == 'distribution') { %> ui-btn-active<% } %>" data-icon="truck">Ausgabestellen</a></li>
        <li><a href="<%- link %>/printer" class="link<% if(activeButton == 'printer') { %> ui-btn-active<% } %>" data-icon="print">Drucker</a></li>
        <li><a href="<%- link %>/table" class="link<% if(activeButton == 'table') { %> ui-btn-active<% } %>" data-icon="grid">Tische</a></li>
    </ul>
</div>