<div data-role="popup" data-position-to="window" id="select-coupon-popup" data-overlay-theme="b" data-theme="b">
    <div data-role="header">
        <h1><%= t.addCoupon %></h1>
    </div>
    <div role="main" class="ui-content">
        <form id="coupon-form">
            <label for="coupon-code"><%= t.code %></label>
            <input type="text" id="coupon-code" name="couponCode" />

            <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
            <a id='coupon-code-verify' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.verify %></a>
        </form>
    </div>
</div>