<div data-role="navbar">
    <ul>
        <li><a href="#manager" class="footer-link <% if(activeButton == 'dashboard') { %> ui-btn-active<% } %>" data-icon="dashboard" id="dashboard">Dashboard</a></li>
        <li><a href="#manager-callback" class="footer-link <% if(activeButton == 'callback') { %> ui-btn-active<% } %>" data-icon="phone" id="callbacks">Rückfragen</a></li>
        <li><a href="#manager-check" class="footer-link <% if(activeButton == 'check') { %> ui-btn-active<% } %>"  data-icon="eye" id="checks">Prüfungen</a></li>
        <li><a href="#manager-groupmessage" class="footer-link <% if(activeButton == 'groupmessage') { %> ui-btn-active<% } %>" data-icon="comment" id="groupmessage">Gruppennachrichten</a></li>
        <li><a href="#manager-statistic" class="footer-link <% if(activeButton == 'statistic') { %> ui-btn-active<% } %>" data-icon="bar-chart-o" id="statistic">Statistik</a></li>
    </ul>
</div>