<ul data-role="listview">
    <li data-role="list-divider">Menü</li>
    <% if(rights & USER_ROLE_ORDER_ADD) { %>
        <li><a href="#order-new" class="header-link ui-btn ui-btn-icon-left ui-icon-plus">Neu</a></li>
    <% } %>
    <% if(rights & USER_ROLE_ORDER_OVERVIEW) { %>
        <li><a href="#order-overview" class="header-link ui-btn ui-btn-icon-left ui-icon-grid">Bestellungen</a></li>
    <% } %>
    <% if(rights & USER_ROLE_INVOICE_OVERVIEW) { %>
        <li><a href="#invoice" class="header-link ui-btn ui-btn-icon-left ui-icon-money">Rechnungen</a></li>
    <% } %>
    <% if(rights & USER_ROLE_DISTRIBUTION_OVERVIEW) { %>
        <li><a href="#distribution" class="header-link ui-btn ui-btn-icon-left ui-icon-star">Ausgabe</a></li>
    <% } %>
    <% if(rights & USER_ROLE_DISTRIBUTION_PREVIEW) { %>
        <li><a href="#distribution-summary" class="header-link ui-btn ui-btn-icon-left ui-icon-table">Ausgabe Übersicht</a></li>
    <% } %>    
    <% if(rights & USER_ROLE_MANAGER_OVERVIEW) { %>
        <li><a href="#manager" class="header-link ui-btn ui-btn-icon-left ui-icon-eye">Manager</a></li>
    <% } %>
    <% if(isAdmin) { %>
        <li><a href="#admin" class="header-link ui-btn ui-btn-icon-left ui-icon-cloud">Admin</a></li>    
    <% } %>
    <li><a id="callRequest" class="ui-btn ui-btn-icon-left ui-icon-phone">Rückruf anfordern</a></li>
    <li><a id="logout" class="ui-btn ui-btn-icon-left ui-icon-power">Logout</a></li>
</ul>