<div data-role="header" data-theme="b">
    <h1>Login</h1>
</div>
<div data-role="content">
    <form id='loginForm' action="#">
    	<fieldset>
            <div data-role="fieldcontain">
                <label for="username" class="ui-hidden-accessible"></label>
                <input type="text" name="username" id="username" placeholder="<%= t.username %>">
            </div>
            <div data-role="fieldcontain">
                <label for="password" class="ui-hidden-accessible"></label>
                <input type="password" name="password" id="password" placeholder="<%= t.password %>">
            </div>
            <div data-role="fieldcontain">
                <label for="rememberMe"><%= t.rememberMe %></label>
                <input type="checkbox" name="rememberMe" id="rememberMe" data-mini="true">
            </div>
            <input type="button" id="submit" data-inline="true" value="<%= t.submit %>">
        </fieldset>
    </form>
</div> 