<div data-role="tabs" id="tabs">
    <div data-role="navbar">
        <ul>
            <li><a>System</a></li>
            <li><a>Manager</a></li>
            <li><a class="ui-icon-plus ui-btn-icon-left">Neu</a></li>
        </ul>
    </div>
    <div>
        <textarea readonly="true" rows="15" class="messages-dialog-textarea"></textarea>
        <div data-role="controlgroup" data-type="horizontal" data-mini="true">
            <input type="text" id="search-control-group" placeholder="Nachricht" data-wrapper-class="controlgroup-textinput-mini ui-btn" class="messages-dialog-input">
            <a data-role="button" >Senden</a>
        </div>
    </div>
    <div >
    </div>
</div>