<ul data-role="listview" data-inset="true" style="min-width:210px;">
    <li data-role="list-divider">Optionen</li>
    <% if(is_admin) { %>
        <li data-icon='cloud'><a id="admin-link">Admin</a></li>
    <% } %>
    <li data-icon="phone"><a id="request-call">Rückruf anfordern</a></li>
    <li data-icon="search"><a id="search-order">Bestellung suchen</a></li>
    <li data-icon="power"><a id="logout-link">Logout</a></li>
</ul>