<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <div data-role="navbar">
        <ul>
            <li><a id="order-pay-show-all" class="ui-btn-active ui-mini">Offen am Tisch</a></li>
            <li><a id="order-pay-show-single" class="ui-mini">Offen von Bestellung</a></li>
        </ul>
    </div>
    <div>
        <a class="ui-btn ui-mini" id='order-pay-button-all'>Alles bezahlen</a>
    </div>
    <div>
            <ul data-role="listview" data-inset="true" id="order-pay-open-orders-list">

            </ul>
    </div>
    <div>
            <h3 class="ui-bar ui-bar-a ui-corner-all">Summe für Rechnung</h3>
            <div class="ui-body ui-body-a ui-corner-all">
                    <h1 style="margin: 0; padding: 0" id="order-pay-invoice-price">0.00 €</h1>
            </div>
    </div>
    <div class="ui-body ui-body-a ui-corner-all">
            <form>
                    <fieldset data-role="controlgroup" data-mini="true">
                            <input type="checkbox" name="order-pay-print" id="order-pay-print">
                            <label for="order-pay-print">Quittung drucken</label>
                            <select name="checkbox-order-pay-printer" id="order-pay-printer">
                                <% printers.each(function(printer){ %>
                                    <option value="<%- printer.get('events_printerid') %>">Drucker: <%- printer.get('name') %></option>
                                <% }) %>
                            </select>
                    </fieldset>
                    <fieldset data-role="controlgroup" data-mini="true">
                            <input type="checkbox" name="order-pay-continue" id="order-pay-continue">
                            <label for="order-pay-continue">auf Seite bleiben</label>
                    </fieldset>

                    <input type="button" id="order-pay-submit" value="Bezahlt">
            </form>
    </div>
</div>