<div data-role="footer" data-theme="b" data-position="fixed" class="nav-footer">
    <div data-role="navbar">
        <ul>
            <li><a href="<%- link %>/detail" class="admin-footer-link<% if(activeButton == 'detail') { %> ui-btn-active<% } %>" data-icon="info">Details</a></li>
            <li><a href="<%- link %>/menu" class="admin-footer-link<% if(activeButton == 'menu') { %> ui-btn-active<% } %>" data-icon="cutlery">Menüs</a></li>
            <li><a href="<%- link %>/table" class="admin-footer-link<% if(activeButton == 'table') { %> ui-btn-active<% } %>" data-icon="grid">Tische</a></li>
            <li><a href="<%- link %>/distribution" class="admin-footer-link<% if(activeButton == 'distribution') { %> ui-btn-active<% } %>" data-icon="truck">Ausgabestellen</a></li>
            <li><a href="<%- link %>/printer" class="admin-footer-link<% if(activeButton == 'printer') { %> ui-btn-active<% } %>" data-icon="print">Drucker</a></li>
        </ul>
    </div>
</div>