<div data-role="footer" data-theme="b" data-position="fixed" class="nav-footer">
    <div data-role="navbar">
        <ul>
            <li><a href="#manager-callback" class="footer-link <% if(activeButton == 'callback') { %> ui-btn-active<% } %>" data-icon="phone" id="manager-footer-callbacks">Rückfragen</a></li>
            <li><a href="#manager-check" class="footer-link <% if(activeButton == 'check') { %> ui-btn-active<% } %>"  data-icon="eye" id="manager-footer-checks">Prüfungen</a></li>
            <li><a href="#manager-groupmessage" class="footer-link <% if(activeButton == 'groupmessage') { %> ui-btn-active<% } %>" data-icon="comment" id="manager-footer-groupmessage">Gruppennachrichten</a></li>
            <li><a href="#manager-statistic" class="footer-link <% if(activeButton == 'statistic') { %> ui-btn-active<% } %>" data-icon="info" id="manager-footer-statistic">Statistik</a></li>
        </ul>
    </div>
</div>