<?php
namespace MyPOS;

const USER_ROLE_MANAGER = 1;
const USER_ROLE_WAITRESS = 2;
const USER_ROLE_DISTRIBUTION = 4;

const ORDER_STATUS_WAITING = 1;
const ORDER_STATUS_IN_PROGRESS = 2;
const ORDER_STATUS_FINISHED = 3;

const MYSQL_TIMEFORMAT = "Y-m-d H:i:s";

const PRINTER_CHARACTER_EURO = "\x1B\x74\x19\xD5";
const PRINTER_LOGO_DEFAULT = 1;
const PRINTER_LOGO_BIT_IMAGE = 2;
const PRINTER_LOGO_BIT_IMAGE_COLUMN = 3;