<div data-role="content">
    <div data-role="header">
        <h2><% if(isNew) { print('Neuer Drucker'); } else { print('Drucker Bearbeiten'); } %></h2>
    </div>
    <form id="form">
        <fieldset data-role="controlgroup">
            <legend>Name:</legend>
            <input type="text" id="name" name="name">
            <label for="name"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Type:</legend>
            <select id="type" name="type">
                <option value="<%- PRINTER_TYPE_NETWORK %>">Netzwerk</option>
                <option value="<%- PRINTER_TYPE_FILE %>">Datei</option>
                <option value="<%- PRINTER_TYPE_WINDOWS %>">Windows</option>
                <option value="<%- PRINTER_TYPE_CUPS %>">CUPS</option>
                <option value="<%- PRINTER_TYPE_DUMMY %>">Dummy</option>
            </select>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Attribute 1:</legend>
            <input type="text" id="attr1" name="">
            <label for="attr1"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Attribute 2:</legend>
            <input type="number" id="attr2" name="">
            <label for="attr2"></label>
        </fieldset>

        <fieldset data-role="controlgroup">
            <legend>Druckergröße:</legend>
            <input type="number" id="charactersPerRow" name="charactersPerRow">
            <label for="charactersPerRow"></label>
        </fieldset>

        <div class="ui-field-contain">
            <a id="save-btn" class="ui-btn">Speichern</a>
        </div>
    </form>
</div>
<div class="nav-footer"></div>