<div data-role="content">
    <div class="nav-header"></div>
    <a id="add-btn" class="ui-btn ui-icon-plus ui-mini ui-btn-icon-left">Hinzufügen</a>
    <table data-role="table" id="admin-event-modify-user-table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th>Name</th>
                <th>Standard</th>
                <th>IP</th>
                <th>Port</th>
                <th>Druckergröße</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody id="printers-list">
        </tbody>
    </table>
</div>
<div class="nav-footer"></div>
<div data-role="popup" id="delete-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Drucker löschen?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind Sie sicher, dass Sie den Drucker löschen wollen? Der Drucker kann nicht mehr verwendet werden!</h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Abbrechen</a>
        <a id='delete-dialog-finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b">Fortfahren</a>
    </div>
</div>