<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <a id="admin-event-modify-user-add-btn" class="ui-btn ui-icon-plus ui-mini ui-btn-icon-left">Hinzufügen</a>
    <table data-role="table" id="admin-event-modify-user-table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th>Benutzername</th>
                <th>Name</th>
                <th>Berechtigungen</th>
                <th>Startgeld</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody>
            <% users.each(function(user){ %>
                <tr>
                    <th><%- user.get('username') %></th>
                    <td><%- user.get('name') %></td>
                    <td><%- user.get('roles') %></td>
                    <td><%- user.get('begin_money') %></td>
                    <td>
                        <a data-events-user-id="<%- user.get('events_userid') %>" class="admin-event-modify-user-edit-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left">Bearbeiten</a>
                        <a data-events-user-id="<%- user.get('events_userid') %>" class="admin-event-modify-user-delete-btn ui-btn ui-icon-delete ui-mini ui-btn-icon-left">Löschen</a>
                    </td>
                </tr>
            <% }); %>
        </tbody>
    </table>
</div>
<div data-role="popup" id="admin-event-modify-user-delete-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Berechtigung löschen?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind Sie sicher, dass Sie die Berechtigung löschen wollen? Der Benutzer kann sich dann für das aktuelle Event nicht mehr einloggen</h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Abbrechen</a>
        <a id='admin-event-modify-user-delete-dialog-finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b">Fortfahren</a>
    </div>
</div>
<%= footer %>