<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <a id="admin-event-modify-distribution-add-btn" class="ui-btn ui-icon-plus ui-mini ui-btn-icon-left">Hinzufügen</a>
    <table data-role="table" id="admin-event-modify-distribution-table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th>Name</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody>
            <% distributions.each(function(distribution){ %>
                <tr>
                    <th><%- distribution.get('name') %></th>
                    <td>
                        <a data-distribution-id="<%- distribution.get('distributions_placeid') %>" class="admin-event-modify-distribution-edit-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left">Bearbeiten</a>
                        <a data-distribution-id="<%- distribution.get('distributions_placeid') %>" class="admin-event-modify-distribution-delete-btn ui-btn ui-icon-delete ui-mini ui-btn-icon-left">Löschen</a>
                    </td>
                </tr>
            <% }); %>
        </tbody>
    </table>
</div>
<div data-role="popup" id="admin-event-modify-distribution-delete-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Ausgabestelle löschen?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind Sie sicher, dass Sie die Ausgabestelle löschen wollen? Der es werden keine Bestellungen mehr abgearbeitet</h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Abbrechen</a>
        <a id='admin-event-modify-distribution-delete-dialog-finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b">Fortfahren</a>
    </div>
</div>
<%= footer %>