<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <a id="admin-menu-typ-add-btn" class="ui-btn ui-icon-plus ui-mini ui-btn-icon-left">Typ Hinzufügen</a>
    <ul data-role="listview" data-inset="true" data-divider-theme="a">
        <% products.each(function(type) { %>
            <li data-role="list-divider">
                <%- type.get('name') %>
                <div data-type-id="<%- type.get('menu_typeid') %>">
                    <a class="admin-menu-group-add-btn ui-btn ui-btn-inline ui-icon-plus ui-mini ui-btn-icon-left">Untergruppe Hinzufügen</a>
                    <a class="admin-menu-typ-edit-btn ui-btn ui-btn-inline ui-icon-edit ui-mini ui-btn-icon-left">Typ Bearbeiten</a>
                    <a class="admin-menu-typ-delete-btn ui-btn ui-btn-inline ui-icon-delete ui-mini ui-btn-icon-left">Typ Löschen</a>
                </div>
            </li>
            <% type.get('groupes').each(function(group) { %>
                <li><a data-group-id="<%- group.get('menu_groupid') %>" class='admin-menu-group-item'><%- group.get('name') %></a></li>
            <% }); %>
        <% }); %>
    </ul>
</div>
<div data-role="popup" id="admin-menu-item-dialog" data-theme="b" data-overlay-theme="b">
    <ul data-role="listview" data-inset="true" style="min-width:210px;">
        <li data-role="list-divider">Optionen</li>
        <li><a id="admin-menu-group-item-edit">Bearbeiten</a></li>
        <li><a id="admin-menu-group-item-delete">Löschen</a></li>
    </ul>
</div>
<div data-role="popup" id="admin-menu-item-delete-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Löschen</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind Sie sicher das das Sie den Typ/die Gruppe löschen wollen? Alle zugeordneten Menüs, Rechnungen, etc. werden gelöscht</h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Abbrechen</a>
        <a id="admin-menu-item-delete-finish-btn" class="ui-btn ui-corner-all ui-shadow ui-btn-b">Fortfahren</a>
    </div>
</div>