<div data-role="content">
    <table data-role="table" id="callback-table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.user %></th>
                <th><%= t.callRequest %></th>
                <th><%= t.phonenumber %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody id="callbacks-list">
        </tbody>
    </table>
</div>