<div data-role="content">
    <table data-role="table" id="callback-table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.user %></th>
                <th><%= t.callRequest %></th>
                <th><%= t.phonenumber %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody>
            <% callbacks.each(function(user){ %>
                <tr>
                    <th><%- user.get('Firstname') %> <%- user.get('Lastname') %></th>
                    <td><%- app.i18n.toDateTime(user.get('CallRequest')) %></td>
                    <td><%- user.get('Phonenumber') %></td>
                    <td><a data-user-cid="<%- user.cid %>" class="done-btn ui-btn ui-icon-check ui-mini ui-btn-icon-left"><%= t.markDone %></a></td>
               </tr>
            <% }); %>
        </tbody>
    </table>
</div>