<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="navbar" id="verified-status" >
        <ul>
            <li><a data-role="tab" data-value="0" class="verify-status-btn <% if(verifiedStatus == '0') { %>ui-btn-active<% } %>"><%= t.openChecks %></a></li>
            <li><a data-role="tab" data-value="1" class="verify-status-btn <% if(verifiedStatus == '1') { %>ui-btn-active<% } %>"><%= t.doneChecks %></a></li>
        </ul>
    </div>
    <table data-role="table" id="table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.table %></th>
                <th><%= t.orderid %></th>
                <th><%= t.menuGroup %></th>
                <th><%= t.amount %></th>
                <th><%= t.singlePrice %></th>
                <th><%= t.detail %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody id="check-list">
        </tbody>
    </table>
</div>
<div data-role="popup" id="info-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1><%= t.details %></h1>
    </div>
    <div role="main" class="ui-content">
        <ul data-role="listview" data-inset="true">
            <li style="white-space: normal;"><%= t.table %>: <span id="info-tablenr"></span></li>
            <li style="white-space: normal;"><%= t.orderid %>: <span id="info-orderid"></span></li>
            <li style="white-space: normal;"><%= t.waiter %>: <span id="info-nameUser"></span></li>
            <li style="white-space: normal;"><%= t.menuGroup %>: <span id="info-menu-group"></span></li>
            <li style="white-space: normal;"><%= t.amount %>: <span id="info-amount"></span></li>
            <li style="white-space: normal;"><%= t.singlePrice %>: <span id="info-single-price"></span><%- i18n.currency %></li>
            <li style="white-space: normal;"><%= t.singlePriceEditedBy %>: <span id="info-single-price-modified-by"></span></li>
            <li style="white-space: normal;"><%= t.detail %>: <span id="info-extra-detail"></span></li>
            <li style="white-space: normal;"><%= t.verified %>: <span id="info-verified"></span></li>
            <li style="white-space: normal;"><%= t.done %>: <span id="info-finished"></span></li>
            <li style="white-space: normal;"><%= t.availability %>: <span id="info-availability"></span></li>
            <li style="white-space: normal;"><%= t.availabilityAmount %>: <span id="info-availability-amount"></span></li>
        </ul>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.close %></a>
    </div>
</div>
<div data-role="popup" id="verify-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1><%= t.edit %></h1>
    </div>
    <div role="main" class="ui-content">
        <ul data-role="listview" data-inset="true">
            <li style="white-space: normal;"><%= t.table %>: <span id="verify-tablenr"></span></li>
            <li style="white-space: normal;"><%= t.orderid %>: <span id="verify-orderid"></span></li>
            <li style="white-space: normal;"><%= t.detail %>: <span id="verify-extra-detail"></span></li>
        </ul>
        <form id="edit-form">
            <div class="ui-field-contain">
                <label for="verify-single-price"><%= t.singlePrice %>:</label>
                <input type="number" name="price" id="verify-single-price" />
            </div>

            <div class="ui-field-contain">
                <label for="verify-menu-group"><%= t.menuGroup %>:</label>
                <select id="verify-menu-group" name="menuGroup">
                    <% products.each(function(type){ %>
                        <optgroup label="<%- type.get('Name') %>">
                            <% type.get('MenuGroup').each(function(group){ %>
                                <option value="<%- group.get('MenuGroupid') %>"><%- group.get('Name') %></option>
                            <% }); %>
                        </optgroup>
                    <% }); %>
                </select>
            </div>

            <div class="ui-field-contain">
                <label for="verify-availability"><%= t.availability %>:</label>
                <select id="verify-availability" name="availability">
                    <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>"><%= i18n.Availability.AVAILABLE %></option>
                    <option value="<%- ORDER_AVAILABILITY_DELAYED %>"><%= i18n.Availability.DELAYED %></option>
                    <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>"><%= i18n.Availability.OUT_OF_ORDER %></option>
                </select>
            </div>

            <div class="ui-field-contain">
                <label for="verify-availability-amount"><%= t.availabilityAmount %>:</label>
                <input type="number" id="verify-availability-amount" placeholder="<%= t.withoutLimit %>" name="availabilityAmount" />
            </div>
        </form>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-inline" data-rel="back"><%= t.cancel %></a>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-inline" id='verify-finished-btn'><%= t.save %></a>
    </div>
</div>
