<div data-role="content">
    <form id="form">
        <fieldset data-role="controlgroup" id="userRoles">
            <legend><%= t.userRoles %>:</legend>
            <div id="userRoles-list">
            </div>
        </fieldset>
        <div class="ui-field-contain">
            <input type="text" id="message" name="message" placeholder="<%= t.message %>" />
            <a id="send" class="ui-btn ui-btn-inline"><%= t.send %></a>
        </div>
    </form>
</div>