<div data-role="content">
    <div class="nav-header"></div>
    <form id="form">
        <fieldset data-role="controlgroup" id="userRoles">
            <legend><%= t.userRoles %>:</legend>
            <% userRoleCollection.each(function(userRole) { %>
                <input type="checkbox" name="userRole" value="<%- userRole.get('UserRoleid') %>" id="checkbox-<%- userRole.get('UserRoleid') %>">
                <label for="checkbox-<%- userRole.get('UserRoleid') %>"><%- userRole.get('Name') %></label>
            <% }); %>
        </fieldset>
        <div class="ui-field-contain">
            <input type="text" id="message" name="message" placeholder="<%= t.message %>" />
            <a id="send" class="ui-btn ui-btn-inline"><%= t.send %></a>
        </div>
    </form>
</div>