<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="navbar" id="verified-status" >
        <ul>
            <li><a data-role="tab"  data-value="0" class="verify-status-btn <% if(verifiedStatus == '0') { %>ui-btn-active<% } %>">Aktuelle Prüfungen</a></li>
            <li><a data-role="tab" data-value="1" class="verify-status-btn <% if(verifiedStatus == '1') { %>ui-btn-active<% } %>">Erledigte Prüfungen</a></li>
        </ul>
    </div>
    <table data-role="table" id="table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th>Tisch</th>
                <th>Bestellnummer</th>
                <th>Menügruppe</th>
                <th>Anzahl</th>
                <th>Einzelpreis</th>
                <th>Detail</th>
                <th>Optionen</th>
            </tr>
        </thead>
        <tbody>
            <% checks.each(function(check){ %>
                <tr>
                    <th><%- check.get('Order').get('EventTable').get('Name') %></th>
                    <td><%- check.get('Orderid') %></td>
                    <td><% if(check.get('MenuGroup') != null) { %> <%- check.get('MenuGroup').get('name') %> <% } %></td>
                    <td><%- check.get('Amount') %></td>
                    <td><% if(check.get('SinglePrice') != null) { %>  <%- parseFloat(check.get('SinglePrice')).toFixed(2) %> <%= i18n.currency %> <% } %></td>
                    <td><%- check.get('ExtraDetail') %></td>
                    <td>
                        <a data-cid="<%- check.cid %>" class="info-btn ui-btn ui-icon-info ui-mini ui-btn-icon-left">Details</a>
                        <% if(check.get('Verified') == 0) { %>
                            <a data-cid="<%- check.cid %>" class="verify-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left">Bearbeiten</a>
                        <% } %>
                    </td>
               </tr>
            <% }); %>
        </tbody>
    </table>
</div>
<div data-role="popup" id="info-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Details</h1>
    </div>
    <div role="main" class="ui-content">
        <ul data-role="listview" data-inset="true">
            <li style="white-space: normal;">Tisch: <span id="info-tablenr"></span></li>
            <li style="white-space: normal;">Bestellnummer: <span id="info-orderid"></span></li>
            <li style="white-space: normal;">Kellner: <span id="info-nameUser"></span></li>
            <li style="white-space: normal;">Menügruppe: <span id="info-menu-group"></span></li>
            <li style="white-space: normal;">Anzahl: <span id="info-amount"></span></li>
            <li style="white-space: normal;">Einzelpreis: <span id="info-single-price"></span><%- i18n.currency %></li>
            <li style="white-space: normal;">Einzelpreis festgelegt von: <span id="info-single-price-modified-by"></span></li>
            <li style="white-space: normal;">Detail: <span id="info-extra-detail"></span></li>
            <li style="white-space: normal;">Geprüft: <span id="info-verified"></span></li>
            <li style="white-space: normal;">Fertig: <span id="info-finished"></span></li>
            <li style="white-space: normal;">Verfügbarkeit: <span id="info-availability"></span></li>
            <li style="white-space: normal;">Verfügbarkeit Anzahl: <span id="info-availability-amount"></span></li>
        </ul>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Schliessen</a>
    </div>
</div>
<div data-role="popup" id="verify-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1>Bearbeiten</h1>
    </div>
    <div role="main" class="ui-content">
        <ul data-role="listview" data-inset="true">
            <li style="white-space: normal;">Tisch: <span id="verify-tablenr"></span></li>
            <li style="white-space: normal;">Bestellnummer: <span id="verify-orderid"></span></li>
        </ul>
        <form>
            <div class="ui-field-contain">
                <label for="verify-single-price">Einzelpreis:</label>
                <input type="number" id="verify-single-price" />
            </div>

            <div class="ui-field-contain">
                <label for="verify-menu-group">Menügruppe:</label>
                <select id="verify-menu-group">
                    <% products.each(function(type){ %>
                        <optgroup label="<%- type.get('Name') %>">
                            <% type.get('MenuGroup').each(function(group){ %>
                                <option value="<%- group.cid %>"><%- group.get('Name') %></option>
                            <% }); %>
                        </optgroup>
                    <% }); %>
                </select>
            </div>

            <div class="ui-field-contain">
                <label for="verify-availability">Verfügbarkeit:</label>
                <select id="verify-availability">
                    <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>">Verfügbar</option>
                    <option value="<%- ORDER_AVAILABILITY_DELAYED %>" >Verspätet</option>
                    <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>">Ausverkauft</option>
                </select>
            </div>

            <div class="ui-field-contain">
                <label for="verify-availability-amount">Verfügbarkeit Anzahl:</label>
                <input type="number" id="verify-availability-amount" placeholder="Ohne Limit" />
            </div>
        </form>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-inline" data-rel="back">Abbrechen</a>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b ui-btn-inline" id='verify-finished-btn'>Speichern</a>
    </div>
</div>
<div class="manager-footer"></div>