<div data-role="header" data-theme="b">
    <h1>Bestellung stornieren</h1>
</div>   
<div data-role="content" role="main">
    Sind sie sicher das die Bestellung <%- order.tableNr %> (<%- order.price %>€) storniert werden soll? 
    Es muss der Betrag <%- order.price %>€ zurück gegeben werden. 
    <a href="#" class="ui-btn ui-corner-all ui-shadow ui-mini ui-icon-delete ui-btn-icon-left" data-rel="back">Abbrechen</a>
    <a href="#" class="ui-btn ui-corner-all ui-shadow ui-mini ui-icon-check ui-btn-icon-left" data-rel="back" >Fortfahren</a>               
</div>