<div data-role="content">
    <div data-role="tabs" id="tabs">
        <div data-role="navbar">
            <ul>
                <li><a data-role="tab" id="tab-btn-order" href="#tab-order"><%= t.currentOrder %></a></li>
                <li><a data-role="tab" id="tab-btn-avaibility" href="#tab-avaibility"><%= t.setAvailabilitys %></a></li>
            </ul>
        </div>
        <div id="tab-order" class="ui-body-d ui-content">
            <div role="main" class="ui-content" id='current-menu'>
                <% if(distributionOrderDetail.get('Order') == null) { %>
                      <h2 style="text-align: center"><%= t.noOrder %></h2>
                <% } else { %>
                    <fieldset style="border: lightgrey solid thin ; border-radius: 10px; padding: 10px">
                        <legend><strong><%= t.order %></strong></legend>
                        <% distributionOrderDetail.get('Order').get('OrderDetails').each(function(orderDetail) { %>
                            <div data-order-type="order-detail" data-amount="<%- orderDetail.get('Amount') %>" data-id="<%- orderDetail.get('OrderDetailid') %>" class="distribution-order ui-grid-a ui-body-a ui-corner-all">
                                <h2>
                                    <%- orderDetail.get('Amount') %>x
                                    <% if(orderDetail.get('Menuid')) { %>
                                        <%- orderDetail.get('Menu').get('Name') %>
                                    <% } else { %>
                                        <%= t.specialOrder %>
                                    <% } %>
                                </h2>
                                <p>
                                    <strong style="white-space: normal;">
                                        <% if(orderDetail.get('MenuSizeid') != ORDER_DEFAULT_SIZEID) { %>
                                            <%- orderDetail.get('MenuSize').get('Name') %>
                                        <% } %>
                                        <% if(orderDetail.get('OrderDetailMixedWiths').length) { %>
                                            <%= t.mixedWith %>:
                                            <% orderDetail.get('OrderDetailMixedWiths').each(function(orderDetailMixedWith) { %>
                                                <%- orderDetailMixedWith.get('Menu').get('Name') %> -
                                            <% }) %>
                                            <% if(orderDetail.get('OrderDetailExtras').length || orderDetail.get('ExtraDetail').length) { %>
                                                ;
                                            <% } %>
                                        <% } %>
                                        <% if( orderDetail.get('OrderDetailExtras').length) { %>
                                            <% orderDetail.get('OrderDetailExtras').each(function(orderDetailExtra, index) { %>
                                                <%- orderDetailExtra.get('MenuPossibleExtra').get('MenuExtra').get('Name') %><% if(index < orderDetail.get('OrderDetailExtras').length - 1) { %>,<% } %>
                                            <% }) %>
                                        <% } %>
                                        <p><%- orderDetail.get('ExtraDetail') %></p>
                                        <% if(!orderDetail.get('Menuid')) { %>
                                            <div data-role="controlgroup" data-type="horizontal"  data-mini="true">
                                                <input type="number" data-type="specialExtra" value="<%- orderDetail.get('AvailabilityAmount') %>" data-id="<%- orderDetail.get('OrderDetailid') %>" name="order-details-special-extra-amount" placeholder="<%= t.withoutLimit %>" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                                <select  data-type="specialExtra" data-id="<%- orderDetail.get('OrderDetailid') %>"  name="order-details-special-extra-status" id="select-native-2">
                                                    <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>"><%= i18n.Availability.AVAILABLE %></option>
                                                    <option value="<%- ORDER_AVAILABILITY_DELAYED %>"><%= i18n.Availability.DELAYED %></option>
                                                    <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>"><%= i18n.Availability.OUT_OF_ORDER %></option>
                                                </select>
                                            </div>
                                        <% } %>
                                    </strong>
                                </p>
                            </div>
                        <% }) %>
                    </fieldset>
                <% } %>
            </div>
            <div class="ui-grid-a">
                <div class="ui-block-a" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;"><%= t.ordersInTodo %></li>
                        <% if(distributionOrderDetail.get('OrdersInTodo')) { %>
                            <% distributionOrderDetail.get('OrdersInTodo').each(function(order) { %>
                                <li style="white-space: normal;"><%- order.get('EventTable').get('Name') %> - <%- app.i18n.toDateTime(order.get('Ordertime')) %> <span class="ui-li-count"><%- order.get('OrderDetailCount') %></span></li>
                            <% }) %>
                        <% } %>
                    </ul>
                </div>
                <div class="ui-block-b" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;"><%= t.informations %></li>
                        <li style="white-space: normal;"><%= t.openOrders %>: <%- distributionOrderDetail.get('OpenOrders') %></li>
                        <li style="white-space: normal;"><%= sprintf(t.doneOrders, {minutes: distributionOrderDetail.get('Minutes')}) %>: <%- distributionOrderDetail.get('DoneOrders') %></li>
                        <li style="white-space: normal;"><%= sprintf(t.newOrders, {minutes: distributionOrderDetail.get('Minutes')}) %>: <%- distributionOrderDetail.get('NewOrders') %></li>
                        <% if(distributionOrderDetail.get('Order')) { %>
                            <li style="white-space: normal;"><%= t.tableNr %>: <strong><%- distributionOrderDetail.get('Order').get('EventTable').get('Name') %></strong></li>
                            <li style="white-space: normal;"><%= t.orderid %>: <%- distributionOrderDetail.get('Order').get('Orderid') %></li>
                            <li style="white-space: normal;"><%= t.ordertime %>: <%- app.i18n.toDateTime(distributionOrderDetail.get('Order').get('Ordertime')) %></li>
                            <li style="white-space: normal;"><%= t.waiter %>: <%- distributionOrderDetail.get('Order').get('UserRelatedByUserid').get('Firstname') %> <%- distributionOrderDetail.get('Order').get('UserRelatedByUserid').get('Lastname') %></li>
                        <% } %>
                    </ul>
                </div>
            </div>
            <% if(distributionOrderDetail.get('Order') != null) { %>
                <div data-role="footer" data-theme="b" data-position="fixed" data-tap-toggle="false">
                    <a id="btn-verify-dialog" style="float:right" id='order-finished' class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check"><%= t.orderDone %></a>
                </div>
            <% } %>
        </div>
        <div id="tab-avaibility">
            <div data-role="collapsible-set">
                <div data-role="collapsible">
                    <h3><%= t.menues %></h3>
                    <p>
                        <ul data-role="listview" id="availability-menues-list">
                            <% products.each(function(type){ %>
                                <li data-role="list-divider"><%- type.get('Name') %></li>
                                <% type.get('MenuGroup').each(function(group){ %>
                                    <% group.get('Menu').each(function(menu){ %>
                                        <li>
                                            <div style="float: left; padding-top: .5em;"><h2><%- menu.get('Name') %></h2></div>
                                            <div data-role="controlgroup" data-type="horizontal" data-mini="true" style="float: right">
                                                <input type="number" data-type="menu" data-id="<%- menu.get('Menuid') %>" value="<%- menu.get('AvailabilityAmount') %>" data-clear-btn="true" placeholder="<%= t.withoutLimit %>" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                                <select type="number" data-type="menu" data-id="<%- menu.get('Menuid') %>">
                                                    <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(menu.get('Availabilityid') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>><%= i18n.Availability.AVAILABLE %></option>
                                                    <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(menu.get('Availabilityid') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>><%= i18n.Availability.DELAYED %></option>
                                                    <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(menu.get('Availabilityid') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>><%= i18n.Availability.OUT_OF_ORDER %></option>
                                                </select>
                                            </div>
                                        </li>
                                    <% }); %>
                                <% }); %>
                            <% }); %>
                        </ul>
                    </p>
                </div>
                <div data-role="collapsible">
                    <h3><%= t.extras %></h3>
                    <p>
                        <ul data-role="listview" id="availability-extras-list">
                            <% distributionOrderDetail.get('MenuExtras').each(function(extra) { %>
                                <li>
                                    <div style="float: left; padding-top: .5em;"><h2><%- extra.get('Name') %></h2></div>
                                    <div data-role="controlgroup" data-type="horizontal" data-mini="true" style="float: right">
                                        <input data-type="extra" type="number" data-id="<%- extra.get('MenuExtraid') %>" value="<%- extra.get('AvailabilityAmount') %>" data-clear-btn="true" placeholder="<%= t.withoutLimit %>" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                        <select data-type="extra" data-id="<%- extra.get('MenuExtraid') %>">
                                            <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(extra.get('Availabilityid') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>><%= i18n.Availability.AVAILABLE %></option>
                                            <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(extra.get('Availabilityid') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>><%= i18n.Availability.DELAYED %></option>
                                            <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(extra.get('Availabilityid') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>><%= i18n.Availability.OUT_OF_ORDER %></option>
                                        </select>
                                    </div>
                                </li>
                            <% }) %>
                        </ul>
                    </p>
                </div>
                <div data-role="collapsible">
                    <h3><%= t.specialExtras %></h3>
                    <p>
                        <ul data-role="listview" id="availability-special-extras-list">
                            <% distributionOrderDetail.get('OrderDetailWithSpecialExtra').each(function(orderDetail) { %>
                                <li>
                                    <div style="float: left; padding-top: .5em;"><h2><%- orderDetail.get('ExtraDetail') %></h2></div>
                                    <div data-role="controlgroup" data-type="horizontal" data-mini="true" style="float: right">
                                        <input type="number" data-type="specialExtra" data-id="<%- orderDetail.get('OrderDetailid') %>" value="<%- orderDetail.get('AvailabilityAmount') %>" data-clear-btn="true" placeholder="<%= t.withoutLimit %>" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                        <select data-type="specialExtra" data-id="<%- orderDetail.get('OrderDetailid') %>">
                                            <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(orderDetail.get('Availabilityid') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>><%= i18n.Availability.AVAILABLE %></option>
                                            <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(orderDetail.get('Availabilityid') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>><%= i18n.Availability.DELAYED %></option>
                                            <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(orderDetail.get('Availabilityid') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>><%= i18n.Availability.OUT_OF_ORDER %></option>
                                        </select>
                                    </div>
                                </li>
                            <% }) %>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div data-role="popup" id="verify-dialog" data-dismissible="false" data-theme="b" data-overlay-theme="b">
    <div data-role="header" data-theme="b">
        <h1><%= t.orderDone %>?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.orderDoneVerifyText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back"><%= t.abort %></a>
        <a id='finished' class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back"><%= t.continue %></a>
    </div>
</div>
