<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <div data-role="tabs" id="distribution-tabs">
        <div data-role="navbar">
            <ul>
                <li><a data-role="tab" href="#distribution-tab-current-order">Aktuelle Bestellung</a></li>
                <li><a data-role="tab" href="#distribution-tab-set-avaibility">Verfügbarkeiten einstellen</a></li>
            </ul>
        </div>
        <div id="distribution-tab-current-order" class="ui-body-d ui-content">
            <div role="main" class="ui-content" id='distribution-current-menu'>
                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2>2x Cola</h2>
                    <p><strong style="white-space: normal;">0.25L</strong></p>
                </div>
                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2>1x Cola</h2>
                    <p><strong style="white-space: normal;">0.5L, gespritzt mit Mineral</strong></p>
                </div>
                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2>4x Ratsherrn</h2>
                    <p><strong style="white-space: normal;">0.5L</strong></p>
                </div>

                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2 style="white-space: normal;">1x Wiener Schnitzel</h2>
                    <p><strong style="white-space: normal;"></strong></p>
                </div>

                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2 style="white-space: normal;">2x Schweinsbraten</h2>
                    <p><strong style="white-space: normal;"></strong></p>
                </div>

                <div class="ui-grid-a ui-body-a ui-corner-all" style="float: left; min-width: 200px; min-height: 107px; margin: 5px; padding: 5px">
                    <h2 style="white-space: normal;">1x Wiener Schnitzel</h2>
                    <p><strong style="white-space: normal;">mit Reis</strong></p>
                </div>
            </div>
            <div class="ui-grid-a">
                <div class="ui-block-a" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;">Bestellungen in Warteliste</li>
                        <li style="white-space: normal;">A38 - 01.04.2016 17:30 <span class="ui-li-count">7</span></li>
                        <li style="white-space: normal;">B32 - 01.04.2016 17:31 <span class="ui-li-count">4</span></li>
                        <li style="white-space: normal;">B8 - 01.04.2016 17:34 <span class="ui-li-count">2</span></li>
                        <li style="white-space: normal;">A23 - 01.04.2016 17:35 <span class="ui-li-count">5</span></li>
                        <li style="white-space: normal;">A15 - 01.04.2016 17:36 <span class="ui-li-count">1</span></li>
                    </ul>
                </div>
                <div class="ui-block-b" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;">Informationen</li>
                        <li style="white-space: normal;">Offene Bestellungen: 12</li>
                        <li style="white-space: normal;">Getätigte fertigstellungen letzten 5 min: 5</li>
                        <li style="white-space: normal;">Neue Bestellungen letzten 5 min: 8</li>
                    </ul>
                </div>
            </div>
            <div data-role="footer" data-theme="b" data-position="fixed" data-tap-toggle="false" >
                <a id="distribution-btn-verify-dialog" style="float:right" id='distribution-order-finished' class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check">Bestellung fertig</a>
            </div>
        </div>
        <div id="distribution-tab-set-avaibility">
            <ul data-role="listview" data-inset="true">
                <li data-role="list-divider">Hauptspeisen</li>
                <li><a>Wiener Schnitzel <span class="ui-li-count">Verfügbar</span></a></li>
                <li><a>Schweinsbratten <span class="ui-li-count">Verfügbar</span></a></li>
                <li><a>Gemüselaibchen <span class="ui-li-count">Verfügbar</span></a></li>
                <li data-role="list-divider">Salate</li>
                <li><a>Kartoffel <span class="ui-li-count">Verfügbar</span></a></li>
                <li><a>Grün <span class="ui-li-count">Verfügbar</span></a></li>
            </ul>
        </div>
    </div>
</div>
<div data-role="popup" id="distribution-status-dialog" data-theme="b">
    <ul data-role="listview" data-inset="true" style="min-width:210px;">
        <li data-role="list-divider">Status auswählen</li>
        <li><a>Verfügbar</a></li>
        <li><a>Verspätet</a></li>
        <li><a>Ausverkauft</a></li>
    </ul>
</div>
<div data-role="popup" id="distribution-verify-dialog" data-overlay-theme="b">
    <div data-role="header" data-theme="b">
        <h1>Bestellung fertig?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind sie sicher das die Bestellung fertig ist?</h3>
        <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Abbrechen</a>
        <a href="#" class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Fortfahren</a>
    </div>
</div>
