<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="tabs" id="tabs">
        <div data-role="navbar">
            <ul>
                <li><a data-role="tab" id="tab-btn-order" href="#tab-order">Aktuelle Bestellung</a></li>
                <li><a data-role="tab" id="tab-btn-avaibility" href="#tab-avaibility">Verfügbarkeiten einstellen</a></li>
            </ul>
        </div>
        <div id="tab-order" class="ui-body-d ui-content">
            <div role="main" class="ui-content" id='current-menu'>
                <% if(true/*ordersSet.get('orders_details').length == 0 &&
                      ordersSet.get('order_details_special_extra').length == 0*/) { %>
                      <h2 style="text-align: center">Zurzeit keine offenen Bestellungen für diese Ausgabestelle vorhanden!</h2>
                <% } else { %>
                    <fieldset style="border: lightgrey solid thin ; border-radius: 10px; padding: 10px">
                        <legend><strong>Bestellung</strong></legend>
                        <% ordersSet.get('orders_details').each(function(order) { %>
                            <div data-order-type="order-detail" data-amount="<%- order.get('amount') %>" data-id="<%- order.get('orders_detailid') %>" class="order ui-grid-a ui-body-a ui-corner-all">
                                <h2><%- order.get('amount') %>x <%- order.get('name') %></h2>
                                <p>
                                    <strong style="white-space: normal;">
                                        <% if(order.get('menu_sizeid') != ORDER_DEFAULT_SIZEID) { %>
                                            <%- order.get('sizeName') %>
                                        <% } %>
                                        <% if(order.get('mixedWithName')) { %>
                                            Gemischt mit: <%- order.get('mixedWithName') %>
                                            <% if(order.get('extrasName') || order.get('extra_detail')) { %>
                                            ;
                                            <% } %>
                                        <% } %>
                                        <%- order.get('extrasName') %>
                                        <%- order.get('extra_detail') %>
                                    </strong>
                                </p>
                            </div>
                        <% }) %>
                        <% ordersSet.get('order_details_special_extra').each(function(order) { %>
                            <div data-order-type="order-detail-special-extra" data-amount="<%- order.get('amount') %>" data-id="<%- order.get('orders_details_special_extraid') %>" class="order ui-grid-a ui-body-a ui-corner-all">
                                <h2><%- order.get('amount') %>x Sonderwunsch</h2>
                                <p>
                                    <strong style="white-space: normal;">
                                        <p><%- order.get('extra_detail') %></p>
                                        <div data-role="controlgroup" data-type="horizontal"  data-mini="true">
                                            <input type="number" data-type="special-extra" value="<%- order.get('availability_amount') %>" data-id="<%- order.get('orders_details_special_extraid') %>" name="order-details-special-extra-amount" placeholder="Ohne Limit" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                            <select  data-type="special-extra" data-id="<%- order.get('orders_details_special_extraid') %>"  name="order-details-special-extra-status" id="select-native-2">
                                                <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>">Verfügbar</option>
                                                <option value="<%- ORDER_AVAILABILITY_DELAYED %>">Verspätet</option>
                                                <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>">Ausverkauft</option>
                                            </select>
                                        </div>
                                    </strong>
                                </p>
                            </div>
                        <% }) %>
                    </fieldset>
                <% } %>
            </div>
            <div class="ui-grid-a">
                <div class="ui-block-a" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;">Bestellungen in Warteliste</li>
                        <% ordersInTodoList.each(function(order) { %>
                            <li style="white-space: normal;"><%- order.get('tableNr') %> - <%- $.format.date(MyPOS.DateFromMysql(order.get('ordertime')), DATE_JS_TIMEFORMAT) %> <span class="ui-li-count"><%- order.get('amount') %></span></li>
                        <% }) %>
                    </ul>
                </div>
                <div class="ui-block-b" style="padding: 5px">
                    <ul data-role="listview" data-inset="true">
                        <li data-role="list-divider" style="white-space: normal;">Informationen</li>
                        <li style="white-space: normal;">Offene Bestellungen: <%- orderDoneInformation.get('open_orders') %></li>
                        <li style="white-space: normal;">Getätigte fertigstellungen letzten <%- MyPOSConfig['Distribution']['OrderProgressTimeRangeMinutes'] %> min: <%- orderDoneInformation.get('done_orders') %></li>
                        <li style="white-space: normal;">Neue Bestellungen letzten <%- MyPOSConfig['Distribution']['OrderProgressTimeRangeMinutes'] %> min: <%- orderDoneInformation.get('new_orders') %></li>
                        <li style="white-space: normal;">Tisch: <strong><%- ordersSet.get('tableNr') %></strong></li>
                        <li style="white-space: normal;">Bestellnummer: <%- ordersSet.get('orderid') %></li>
                        <li style="white-space: normal;">Bestellzeit: <%- ordersSet.get('ordertime') %></li>
                        <li style="white-space: normal;">Kellner: <%- ordersSet.get('waitress') %></li>
                    </ul>
                </div>
            </div>
            <div data-role="footer" data-theme="b" data-position="fixed" data-tap-toggle="false">
                <a id="btn-verify-dialog" style="float:right" id='order-finished' class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check">Bestellung fertig</a>
            </div>
        </div>
        <div id="tab-avaibility">
            <div data-role="collapsible-set">
                <div data-role="collapsible">
                    <h3>Menüs</h3>
                    <p>
                        <ul data-role="listview" id="availability-menues-list">
                            <% _.each(menuesArray, function(menues, typeName) { %>
                                <li data-role="list-divider"><%- typeName %></li>
                                <% _.each(menues, function(menu) { %>
                                    <li>
                                        <div style="float: left; padding-top: .5em;"><h2><%- menu.get('name') %></h2></div>
                                        <div data-role="controlgroup" data-type="horizontal"  data-mini="true"  style="float: right">
                                            <input type="number" data-type="menu" data-id="<%- menu.get('menuid') %>" value="<%- menu.get('availability_amount') %>" data-clear-btn="true" placeholder="Ohne Limit" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                            <select type="number" data-type="menu" data-id="<%- menu.get('menuid') %>">
                                                <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(menu.get('availability') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>>Verfügbar</option>
                                                <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(menu.get('availability') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>>Verspätet</option>
                                                <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(menu.get('availability') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>>Ausverkauft</option>
                                            </select>
                                        </div>
                                    </li>
                                <% }) %>
                            <% }) %>
                        </ul>
                    </p>
                </div>
                <div data-role="collapsible">
                    <h3>Extras</h3>
                    <p>
                        <ul data-role="listview" id="availability-extras-list">
                            <% productsAvailability.get('extras').each(function(extra) { %>
                                <li>
                                    <div style="float: left; padding-top: .5em;"><h2><%- extra.get('name') %></h2></div>
                                    <div data-role="controlgroup" data-type="horizontal"  data-mini="true"  style="float: right">
                                        <input data-type="extra" type="number" data-id="<%- extra.get('menu_extraid') %>" value="<%- extra.get('availability_amount') %>" data-clear-btn="true" placeholder="Ohne Limit" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                        <select data-type="extra" data-id="<%- extra.get('menu_extraid') %>">
                                            <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(extra.get('availability') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>>Verfügbar</option>
                                            <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(extra.get('availability') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>>Verspätet</option>
                                            <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(extra.get('availability') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>>Ausverkauft</option>
                                        </select>
                                    </div>
                                </li>
                            <% }) %>
                        </ul>
                    </p>
                </div>
                <div data-role="collapsible">
                    <h3>Spezial Extras</h3>
                    <p>
                        <ul data-role="listview" id="availability-special-extras-list">
                            <% productsAvailability.get('special_extras').each(function(specialExtra) { %>
                                <li>
                                    <div style="float: left; padding-top: .5em;"><h2><%- specialExtra.get('extra_detail') %></h2></div>
                                    <div data-role="controlgroup" data-type="horizontal"  data-mini="true"  style="float: right">
                                        <input type="number" data-type="special-extra" data-id="<%- specialExtra.get('orders_details_special_extraid') %>" value="<%- specialExtra.get('availability_amount') %>" data-clear-btn="true" placeholder="Ohne Limit" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important;">
                                        <select data-type="special-extra" data-id="<%- specialExtra.get('orders_details_special_extraid') %>">
                                            <option value="<%- ORDER_AVAILABILITY_AVAILABLE %>" <% if(specialExtra.get('availability') == ORDER_AVAILABILITY_AVAILABLE) { print('selected="true"')} %>>Verfügbar</option>
                                            <option value="<%- ORDER_AVAILABILITY_DELAYED %>" <% if(specialExtra.get('availability') == ORDER_AVAILABILITY_DELAYED) { print('selected="true"')} %>>Verspätet</option>
                                            <option value="<%- ORDER_AVAILABILITY_OUT_OF_ORDER %>" <% if(specialExtra.get('availability') == ORDER_AVAILABILITY_OUT_OF_ORDER) { print('selected="true"')} %>>Ausverkauft</option>
                                        </select>
                                    </div>
                                </li>
                            <% }) %>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div data-role="popup" id="verify-dialog" data-dismissible="false" data-theme="b" data-overlay-theme="b">
    <div data-role="header" data-theme="b">
        <h1>Bestellung fertig?</h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title">Sind sie sicher das die Bestellung fertig ist?</h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Abbrechen</a>
        <a id='finished' class="ui-btn ui-corner-all ui-shadow ui-btn-inline ui-btn-b" data-rel="back">Fortfahren</a>
    </div>
</div>
