 <div data-role="content">
    <div class="nav-header"></div>
    <div>
        <label for="maturityDate"><%= t.maturityDate %></label>
        <input class="form-control" id="maturityDate" type="text" data-role="datebox" data-options='{"mode":"datebox","useFocus":true}'/>

        <label for="customerid"><%= t.customerid %>:</label>
        <input type="number" id="customerid" data-mini="true" />
        <input type="button" id="use-customer" value="<%= t.selectCustomer%>" data-mini="true">

        <label for="typeid"><%= t.type %>:</label>
        <select id="typeid" data-mini="true">
            <% invoiceTypeList.each(function(invoiceType) { %>
                <option value="<%- invoiceType.get('InvoiceTypeid') %>"><%- i18n.InvoiceType[invoiceType.get('Name')] %></option>
            <% }) %>
        </select>

        <div style="padding-top: 2em">
            <a id="add-entry" class="ui-btn ui-mini ui-btn-icon-right ui-icon-plus"><%= t.addEntry %></a>
            <table data-role="table" id="invoice-item-table" class="ui-responsive table-stroke table-stripe">
                <thead>
                    <tr>
                        <th><%= t.description %></th>
                        <th><%= t.amount %></th>
                        <th><%= t.price %></th>
                        <th><%= t.tax %></th>
                        <th><%= t.sum %></th>
                        <th><%= t.options %></th>
                    </tr>
                </thead>
                <tbody id="invoice-item-list">
                </tbody>
            </table>
        </div>

        <div>
            <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.sum %></h3>
            <div class="ui-body ui-body-a ui-corner-all">
                <h1 style="margin: 0; padding: 0" id='total'><%- app.i18n.toCurrency(0) %></h1>
            </div>
        </div>
    </div>
</div>
<div data-role="popup" id="form-dialog" data-overlay-theme="b" data-theme="b">
    <div data-role="header"><h1><%= t.addEntry %></h1></div>
    <div role="main" class="ui-content">
        <form id="add-form">
            <div data-role="fieldcontain">
                <label for="description"><%= t.description %>:</label>
                <input type="text" id="description" name="description" data-mini="true"/>
            </div>

            <div data-role="fieldcontain">
                <label for="amount"><%= t.amount %>:</label>
                <input type="number" id="amount" name="amount" data-mini="true"/>
            </div>

            <div data-role="fieldcontain">
                <label for="price"><%= t.price %>:</label>
                <input type="number" id="price" name="price" data-mini="true"/>
            </div>

            <div data-role="fieldcontain">
                <label for="tax"><%= t.tax %>%:</label>
                <input type="number" id="tax" name="tax" data-mini="true"/>
            </div>
        </form>

        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='saveItem' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.save %></a>
    </div>
</div>
<div data-role="popup" id="verify-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a"><h1><%= t.invoiceFinished %></h1></div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.invoiceFinishedVerifyText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed">
    <a id="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="save" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check" style="float:right"><%= t.save %></a>
</div>