 <div data-role="content">
    <div class="nav-header"></div>
    <div data-role="popup" data-position-to="window" id="add-coupon-popup" data-overlay-theme="b" data-theme="b">
         <div data-role="header">
            <h1><%= t.addCoupon %></h1>
        </div>
        <div role="main" class="ui-content">
            <label for="coupon-code"><%= t.code %></label>
            <input type="text" id="coupon-code" />

            <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
            <a id='coupon-code-verify' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.verify %></a>
        </div>
    </div>
    <div>
        <label for="invoiceid"><%= t.invoiceid %>:</label>
        <input type="number" id="invoiceid" data-mini="true" />
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed">
    <a id="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="search" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-search" style="float:right"><%= t.search %></a>
</div>