<div data-role="content">
    <div class="nav-header"></div>
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider" style="white-space: normal;"><%= t.informations %></li>
        <li style="white-space: normal;"><b><%= t.invoiceid %>:</b> <%- invoiceInfo.get('Invoiceid') %></li>
        <li style="white-space: normal;"><b><%= t.invoiceType %>:</b> <%- i18n.InvoiceType[invoiceInfo.get('InvoiceType').get('Name')] %></li>
        <li style="white-space: normal;"><b><%= t.date %>:</b> <%- f.toDateTime(invoiceInfo.get('Date')) %></li>
        <li style="white-space: normal;"><b><%= t.creator %>:</b> <%- invoiceInfo.get('User').get('Firstname') %> <%- invoiceInfo.get('User').get('Lastname') %></li>
        <li style="white-space: normal;"><b><%= t.sum %>:</b> <%- f.toCurrency(invoiceInfo.get('Amount')) %></li>
        <li style="white-space: normal;"><b><%= t.maturityDate %>:</b> <%-  f.toDateTime(invoiceInfo.get('MaturityDate')) %></li>
        <li style="white-space: normal;"><b><%= t.amountPayed %>:</b> <%- f.toCurrency(invoiceInfo.get('AmountRecieved')) %></li>
        <li style="white-space: normal;"><b><%= t.status %>:</b>
            <%
                if(invoiceInfo.get('CanceledInvoiceid')) {
                    print(t.canceled);
                } else {
                    print(t.entry);
                }
            %>
            -
            <% if(invoiceInfo.get('PaymentFinished')) { %>
                <span style="color: green;"><%= t.payed %></span>
            <% } else { %>
                <span style="color: red;"><%= t.unpayed %></span>
            <% } %>
        </li>
        <li style="white-space: normal;">
            <b><%= t.contactInformation %>:</b><br/>
            <% let contact = invoiceInfo.get('EventContactRelatedByEventContactid'); %>
            <%- contact.get('Title') %><br/>
            <%- contact.get('Name') %><br/>
            <% if(contact.get('ContactPerson')) { print(contact.get('ContactPerson') + '<br/>') } %>
            <%- contact.get('Address') %><br/>
            <% if(contact.get('Address2')) { print(contact.get('Adress2') + '<br/>') } %>
            <%- contact.get('Zip') %> <%- contact.get('City') %>
            <% if(contact.get('TaxIdentificationNr')) { print('<br/>UID: ' + contact.get('TaxIdentificationNr')) } %>
            <% if(contact.get('Telephon')) { print('<br/>Telefon: ' + contact.get('Telephon')) } %>
            <% if(contact.get('Fax')) { print('<br/>Fax: ' + contact.get('Fax')) } %>
            <% if(contact.get('Email')) { print('<br/>Email: ' + contact.get('Email')) } %>
        </li>
        <li style="white-space: normal;">
            <b><%= t.bankInformation %>:</b><br/>
            <% let bank = invoiceInfo.get('EventBankinformation'); %>
            Name: <%- bank.get('Name') %><br/>
            IBAN: <%- bank.get('Iban') %><br/>
            BIC: <%- bank.get('Bic') %>
        </li>
        <li style="white-space: normal;">
            <b><%= t.customer %>:</b><br/>
            <% if(invoiceInfo.get('CustomerEventContactid')) { %>
                <% let customer = invoiceInfo.get('EventContactRelatedByCustomerEventContactid'); %>
                <%- customer.get('Title') %><br/>
                <%- customer.get('Name') %><br/>
                <% if(customer.get('ContactPerson')) { print(customer.get('ContactPerson') + '<br/>') } %>
                <%- customer.get('Address') %><br/>
                <% if(customer.get('Address2')) { print(customer.get('Adress2') + '<br/>') } %>
                <%- customer.get('Zip') %> <%- customer.get('City') %>
                <% if(customer.get('TaxIdentificationNr')) { print('<br/>UID: ' + customer.get('TaxIdentificationNr')) } %>
                <% if(customer.get('Telephon')) { print('<br/>Telefon: ' + customer.get('Telephon')) } %>
                <% if(customer.get('Fax')) { print('<br/>Fax: ' + customer.get('Fax')) } %>
                <% if(customer.get('Email')) { print('<br/>Email: ' + customer.get('Email')) } %>
            <% } else { %>
                <%= t.noCustomer %>
            <% } %>
        </li>
    </ul>
    <div>
        <div class="ui-grid-a ui-responsive">
            <div class="ui-block-a"><h4><%= t.invoiceItem %></h4></div>
            <div class="ui-block-b">
                <% if(!invoiceInfo.get('CanceledInvoiceid') && invoiceInfo.get('InvoiceTypeid') != INVOICE_TYPE_CANCELLATION) { %>
                    <a id="cancel-btn" class="ui-btn ui-mini ui-icon-delete ui-btn-icon-left"><%= t.cancelInvoice %></a>
                <% } %>
            </div>
        </div>
        <table data-role="table" class="ui-responsive table-stroke">
            <thead>
                <tr>
                    <th><%= t.description %></th>
                    <th><%= t.amount %></th>
                    <th><%= t.price %></th>
                    <th><%= t.sum %></th>
                    <th><%= t.tax %></th>
                </tr>
            </thead>
            <tbody>
                <% invoiceInfo.get('InvoiceItems').each(function(invoiceItem) { %>
                    <tr>
                        <th><%- invoiceItem.get('Description') %></th>
                        <td><%- invoiceItem.get('Amount') %></td>
                        <td><%- f.toCurrency(invoiceItem.get('Price')) %></td>
                        <td><%- f.toCurrency(invoiceItem.get('Amount') * invoiceItem.get('Price')) %></td>
                        <td><%- invoiceItem.get('Tax') %>%</td>
                    </tr>
                <% }); %>
            </tbody>
        </table>
    </div>
    <div>
        <div class="ui-grid-a ui-responsive">
            <div class="ui-block-a"><h4><%= t.payments %></h4></div>
            <div class="ui-block-b">
                <% if(!invoiceInfo.get('CanceledInvoiceid') && invoiceInfo.get('InvoiceTypeid') != INVOICE_TYPE_CANCELLATION) { %>
                    <a id="add-payment-btn" class="ui-btn ui-mini ui-icon-euro ui-btn-icon-left"><%= t.bookPayment %></a>
                <% } %>
            </div>
        </div>
        <table data-role="table" class="ui-responsive table-stroke">
            <thead>
                <tr>
                    <th><%= t.date %></th>
                    <th><%= t.paymentType %></th>
                    <th><%= t.entryCreator %></th>
                    <th><%= t.sum %></th>
                    <th><%= t.usedCoupons %></th>
                </tr>
            </thead>
            <tbody>
                <% invoiceInfo.get('PaymentRecieveds').each(function(paymentRecieved) { %>
                    <tr>
                        <th><%- f.toDate(paymentRecieved.get('Date')) %></th>
                        <td><%- i18n.PaymentType[paymentRecieved.get('PaymentType').get('Name')] %></td>
                        <td><%- paymentRecieved.get('User').get('Firstname') %> <%- paymentRecieved.get('User').get('Lastname') %></td>
                        <td><%- f.toCurrency(paymentRecieved.get('Amount')) %></td>
                        <td>
                            <% paymentRecieved.get('PaymentCoupons').each(function(paymentCoupon) { %>
                                <%= t.coupon %>: <%- paymentCoupon.get('Coupon').get('Code') %>,
                                <%= t.value %>: <%- f.toCurrency(paymentCoupon.get('ValueUsed')) %><br/>
                            <% }); %>
                        </td>
                    </tr>
                <% }); %>
            </tbody>
        </table>
    </div>
    <div>
        <div class="ui-block-a"><h4><%= t.warnings %></h4></div>
        <table data-role="table" class="ui-responsive table-stroke">
            <thead>
                <tr>
                    <th><%= t.date %></th>
                    <th><%= t.warningType %></th>
                    <th><%= t.maturityDate %></th>
                    <th><%= t.warningValue %></th>
                </tr>
            </thead>
            <tbody>
                <% invoiceInfo.get('InvoiceWarnings').each(function(invoiceWarning) { %>
                    <tr>
                        <th><%- f.toDate(invoiceWarning.get('WarningDate')) %></th>
                        <td><%- invoiceWarning.get('InvoiceWarningType').get('Name') %></td>
                        <td><%- f.toDate(invoiceWarning.get('MaturityDate')) %></td>
                        <td><%- f.toCurrency(invoiceWarning.get('WarningValue')) %></td>
                    </tr>
                <% }); %>
            </tbody>
        </table>
    </div>
</div>
<div data-role="popup" id="dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1 id="dialog-title"><%= t.cancelInvoice %></h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title" id="dialog-text"><%= t.cancelInvoiceText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
        <a id='dialog-continue' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed" >
    <a data-rel="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
</div>