 <div data-role="content">
    <div class="nav-header"></div>
    <div>
        <label for="maturityDate"><%= t.maturityDate %></label>
        <input class="form-control" id="maturityDate" type="text" data-role="datebox" data-options='{"mode":"datebox","useFocus":true}'/>

        <label for="customerid"><%= t.customerid %>:</label>
        <input type="number" id="customerid" data-mini="true" />
        <input type="button" id="use-customer" value="<%= t.selectCustomer%>" data-mini="true">

        <label for="typeid"><%= t.type %>:</label>
        <select id="typeid" data-mini="true">
            <% invoiceTypeList.each(function(invoiceType) { %>
                <option value="<%- invoiceType.get('InvoiceTypeid') %>"><%- i18n.InvoiceType[invoiceType.get('Name')] %></option>
            <% }) %>
        </select>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed">
    <a id="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="save" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-search" style="float:right"><%= t.save %></a>
</div>