 <div data-role="content">
    <div>
        <fieldset id="status" data-role="controlgroup" data-type="horizontal" data-mini="true">
            <legend><%= t.status %>:</legend>
            <input type="radio" name="status" id="all" value="all">
            <label for="all"><%= t.all %></label>
            <input type="radio" name="status" id="paid" value="paid">
            <label for="paid"><%= t.paid %></label>
            <input type="radio" name="status" id="unpaid" value="unpaid">
            <label for="unpaid"><%= t.unpaid %></label>
        </fieldset>

        <fieldset id="canceled" data-role="controlgroup" data-type="horizontal" data-mini="true">
            <legend><%= t.canceled %>:</legend>
            <input type="radio" name="canceled" id="null" value="">
            <label for="null"><%= t.all %></label>
            <input type="radio" name="canceled" id="true" value="true">
            <label for="true"><%= t.yes %></label>
            <input type="radio" name="canceled" id="false" value="false">
            <label for="false"><%= t.no %></label>
        </fieldset>

        <label for="invoiceid"><%= t.invoiceid %>:</label>
        <input type="number" id="invoiceid" data-mini="true" />

        <label for="customerid"><%= t.customerid %>:</label>
        <input type="number" id="customerid" data-mini="true" />
        <input type="button" id="select-customer" value="<%= t.selectCustomer%>" data-mini="true">

        <label for="typeid"><%= t.type %>:</label>
        <select id="typeid" data-mini="true">
        </select>

        <fieldset data-role="controlgroup" data-type="vertical" data-mini="true">
            <legend><%= t.invoicePeriod %>:</legend>
            <label for="from"><%= t.from %></label>
            <input class="form-control" id="from" type="text" data-role="datebox" data-options='{"mode":"datebox","useFocus":true}'/>
            <label for="to"><%= t.to %></label>
            <input class="form-control" id="to" type="text" data-role="datebox" data-options='{"mode":"datebox","useFocus":true}'/>
        </fieldset>

        <label for="userid"><%= t.waiter %>:</label>
        <select id="userid" data-mini="true">
            <option value="*"><%= t.all %></option>
            <% userList.each(function(user) { %>
                <option value="<%- user.get('Userid') %>"><%- user.get('Firstname') %> <%- user.get('Lastname') %></option>
            <% }) %>
        </select>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed">
    <a id="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="search" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-search" style="float:right"><%= t.search %></a>
</div>