 <div data-role="content">
    <div>
        <form id='payment-form'>
            <label for="paymentValue"><%= t.paymentValue %>:</label>
            <input type="number" id="paymentValue" name='paymentValue' data-mini="true" value='0' />

            <label for="typeid"><%= t.type %>:</label>
            <select id="typeid" data-mini="true">
                <% paymentTypes.each(function(paymentType) { %>
                    <option value="<%- paymentType.get('PaymentTypeid') %>"><%- i18n.PaymentType[paymentType.get('Name')] %></option>
                <% }) %>
            </select>
        </form>

        <fieldset data-role="controlgroup" data-mini="true" style="padding-top: 2em">
            <input type="button" id="use-coupon" value="<%= t.addCoupon %>">

            <table data-mode="reflow" id='coupons-table' data-role="table" class="ui-responsive table-stroke">
                <thead>
                    <tr>
                        <th><%= t.code %></th>
                        <th><%= t.value %></th>
                        <th><%= t.consumed %></th>
                        <th><%= t.options %></th>
                    </tr>
                </thead>
                <tbody id="coupons-item-list">
                </tbody>
            </table>
        </fieldset>

        <div>
            <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.sum %></h3>
            <div class="ui-body ui-body-a ui-corner-all">
                <h3 style="margin: 0; padding: 0"><span id='totalPaymentValue'><%- app.i18n.toCurrency(0) %></span> <%= t.paymentValue %> + <span id='totalCouponValue'><%- app.i18n.toCurrency(0) %></span> <%= t.couponsValue %> =</h3>
                <h1 style="margin: 0; padding: 0" id='totalSum'><%- app.i18n.toCurrency(0) %></h1>
            </div>
        </div>
    </div>
</div>
<div data-role="popup" data-position-to="window" id="add-coupon-popup" data-overlay-theme="b" data-theme="b">
    <div data-role="header">
       <h1><%= t.addCoupon %></h1>
   </div>
   <div role="main" class="ui-content">
       <label for="coupon-code"><%= t.code %></label>
       <input type="text" id="coupon-code" />

       <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
       <a id='coupon-code-verify' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.verify %></a>
   </div>
</div>

<div data-role="popup" data-position-to="window" id="edit-coupon-popup" data-overlay-theme="b" data-theme="b">
    <div data-role="header">
       <h1><%= t.editCoupon %></h1>
   </div>
   <div role="main" class="ui-content">
       <label for="valueToUse"><%= t.valueToUse %></label>
       <input type="number" id="valueToUse" />

       <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
       <a id='coupon-edit-continue' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
   </div>
</div>
<div data-role="popup" id="verify-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a"><h1><%= t.paymentFinished %></h1></div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.paymentFinishedVerifyText %></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed">
    <a id="back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="save" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check" style="float:right"><%= t.save %></a>
</div>