<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <pre>
        Rückrufanfragen
        Prüfen von Sonderwünschen -> festlegen des Preises
        Zugriff auf alle Bestellungen (kann Preise manuell anpassen für einzelen Bestellungen, kann Status prüfen)
        Chatnachrichten verwalten bzw. nachrichten an bestimmte Benutzergruppen senden
        Grafische Auswertung über:
            Offene Bestellungen
            Stundenansicht +/-,
            Wieviel erledigt wurde
            durchschnittliche Wartezeit pro Bestellung
            Sortierbar nach Menügruppe
            Was wurde am meisten bestellt bzw. welches Menü/Menügruppe wird am meisten bestellt oder wartet am längsten.
        Auslastung der Tische
        Statuse manuell setzen
        Kassenstand pro Kassier für Abrechnung
        Jeder beliebige weiter Statistik
    </pre>
    Dashboard!!!!
</div>
<%= footer %>