<div class="ui-grid-a">
    <div class="ui-block-a">
        <h2 style="white-space: normal;"><%- name %></h2>
        <p><strong style="white-space: normal;"><%- extras %></strong></p>
    </div>
    <div class="ui-block-b" style="top: 1em; right: 0em; text-align: right; font-size: .75em; font-weight: 400; margin: .6em 0;">
        <% if(mode == 'pay') { %>
	        in Rechnung: <strong><%- amount %></strong>
	        <br/>
	        Offen: <strong><%- open %></strong>
	        <br/>
        <% } else { %>
	        Anzahl: <strong><%- amount %></strong>
	        <br/>
        <% } %>

        <% if(isSpecialOrder == true) { %>
            <strong>Preis wird von<br/>Manager noch<br/>festgelegt</strong>
        <% } else { %>
            Einzelpreis: <strong><%- parseFloat(price).toFixed(2) %>€</strong>
            <br/>
            Gesamt: <strong><%- parseFloat(totalPrice).toFixed(2) %>€</strong>
        <% } %>
        <% if(!skipCounts) { %>
            <br/>
            <a data-menu-typeid="<%- menu_typeid %>" data-index="<%- index %>" class="order-item-up ui-btn ui-btn-inline ui-icon-plus ui-btn-icon-notext">+</a>
            <a data-menu-typeid="<%- menu_typeid %>" data-index="<%- index %>" class="order-item-down ui-btn ui-btn-inline ui-icon-minus ui-btn-icon-notext">-</a>
        <% } %>
    </div>
</div>
<% if(typeof statusInformation !== 'undefined') { %>
    <div class="ui-grid-solo">
        <div class="ui-block-a">
            <% if(status == ORDER_STATUS_WAITING) { %>
                <p>Warteschlange Pos <%- rank %></p>
            <% } else if(status == ORDER_STATUS_IN_PROGRESS) { %>
                <p style="color:orange;">
                    in Bearbeitung seit
                    <%- $.format.date(MyPOS.DateFromMysql(in_progress_begin), DATE_JS_TIMEFORMAT) %>
                    Pos <%- rank %>
                </p>
                <p>Bearbeiter: <%- handled_by_name %></p>
                <p>Erhalten: <%- amount_recieved_total %></p>
                <p>Auslieferungen:</p>
                <ul class="ui-mini">
                    <% _.each(amount_recieved, function(current_amount, current_date){ %>
                        <li><%- $.format.date(MyPOS.DateFromMysql(current_date), DATE_JS_TIMEFORMAT) %>: <%- current_amount %></li>
                    <% }) %>
                </ul>
            <% } else if(status == ORDER_STATUS_FINISHED) { %>
                <p style="color:green;">
                        Fertig - Bearbeitet von
                        <%- $.format.date(MyPOS.DateFromMysql(in_progress_begin), DATE_JS_TIMEFORMAT) %>
                        bis
                        <%- $.format.date(MyPOS.DateFromMysql(in_progress_done), DATE_JS_TIMEFORMAT) %>
                </p>
                <p>Bearbeiter: <%- handled_by_name %></p>
                <p>Erhalten: <%- amount_recieved_total %></p>
                <p>Auslieferungen:</p>
                <ul class="ui-mini">
                    <% _.each(amount_recieved, function(current_amount, current_date){ %>
                        <li><%- $.format.date(MyPOS.DateFromMysql(current_date), DATE_JS_TIMEFORMAT) %>: <%- current_amount %></li>
                    <% }) %>
                </ul>
            <% } %>
        </div>
    </div>
<% } %>
