<div data-role="content">
	<div class="ui-grid-b">
	    <div class="ui-block-a"><a data-role="button" class="table-nr">1</a></div>
	    <div class="ui-block-b"><a data-role="button" class="table-nr">2</a></div>
	    <div class="ui-block-c"><a data-role="button" class="table-nr">3</a></div>
	</div>
	<div class="ui-grid-b">
	    <div class="ui-block-a"><a data-role="button" class="table-nr">4</a></div>
	    <div class="ui-block-b"><a data-role="button" class="table-nr">5</a></div>
	    <div class="ui-block-c"><a data-role="button" class="table-nr">6</a></div>
	</div>
	<div class="ui-grid-b">
	    <div class="ui-block-a"><a data-role="button" class="table-nr">7</a></div>
	    <div class="ui-block-b"><a data-role="button" class="table-nr">8</a></div>
	    <div class="ui-block-c"><a data-role="button" class="table-nr">9</a></div>
	</div>
	<div class="ui-grid-b">
	    <div class="ui-block-a"></div>
	    <div class="ui-block-b"><a data-role="button" class="table-nr">0</a></div>
	    <div class="ui-block-c"></div>
	</div>
	<div class="ui-grid-b">
	    <div class="ui-block-a"><a data-role="button" class="table-nr">A</a></div>
	    <div class="ui-block-b"><a data-role="button" class="table-nr">B</a></div>
	    <div class="ui-block-c"><a data-role="button" class="table-nr">C</a></div>
	</div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed" >		
	<a style="float:left" id='tableNrClear' class="ui-btn ui-corner-all ui-btn-inline ui-mini  ui-btn-icon-left ui-icon-delete"><%= t.delete %></a>
	<a style="float:right" id='next' class="ui-btn ui-corner-all ui-btn-inline ui-mini  ui-btn-icon-right ui-icon-carat-r"><%= t.next %></a>
	<h1 style="float:left"  id="tableNr"></h1>			
	<div style="clear: both;"></div>		
</div>	