<div data-role="content">
    <div data-role="popup" data-overlay-theme="b" data-theme="b" data-position-to="window" id="success-popup" class="ui-content">
         <h3><%= t.paymentSuccessfull %></h3>
    </div>
    <div data-role="navbar">
        <ul>
            <li><a id="show-all" class="ui-btn-active ui-mini"><%= t.openOnTable %></a></li>
            <li><a id="show-single" class="ui-mini"><%= t.openOffOrder %></a></li>
        </ul>
    </div>
    <div>
        <a class="ui-btn ui-mini" id='button-all'><%= t.payAll %></a>
    </div>
    <div>
        <ul data-role="listview" data-inset="true" id="open-orders-list"></ul>
    </div>
    <div>
        <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.sumForInvoice %></h3>
        <div class="ui-body ui-body-a ui-corner-all">
            <h1 style="margin: 0; padding: 0" id="invoice-price">0.00 <%= i18n.currency %></h1>
            <div id="invoice-price-without-coupon"></div>
        </div>
    </div>
    <div class="ui-body ui-body-a ui-corner-all">
        <form>
            <fieldset data-role="controlgroup" data-mini="true">
                <input type="checkbox" name="continue" id="continue" checked="true">
                <label for="continue"><%= t.stayOnPage %></label>
            </fieldset>
            <div data-role="collapsible" data-inset="false" data-mini="true" data-collapsed-icon="carat-d" data-expanded-icon="carat-u">
                <h4><%= t.moreOptions %></h4>
                <fieldset data-role="controlgroup" data-mini="true">
                    <input type="button" id="use-coupon" value="<%= t.addCoupon %>">
                    <ul data-role="listview" data-inset="true" id="coupons-list"></ul>
                </fieldset>
                <fieldset data-role="controlgroup" data-mini="true">
                    <input type="checkbox" name="print" id="print">
                    <label for="print" id="print-receipt-text"><%= t.printReceipt %></label>
                    <select name="checkbox-printer" id="printer">
                    </select>
                </fieldset>
                <fieldset data-role="controlgroup" data-mini="true">
                    <select name="checkbox-printer" id="paymentTypeList">
                    </select>
                </fieldset>
                <fieldset data-role="controlgroup" data-mini="true">
                    <input type="button" id="use-customer" value="<%= t.selectCustomer%>">
                    <div id="selected-customer-display" style="text-align: center"></div>
                </fieldset>
            </div>
            <input type="button" id="submit" value="<%= t.create %>">
        </form>
    </div>
</div>