<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="tabs" id="tabs">
        <div data-role="navbar" data-iconpos="notext" id="tabs-navbar" >
            <ul>
                <% products.each(function(type){ %>
                    <li><a data-role="tab"  href="#<%- type.get('MenuTypeid') %>"><%- type.get('Name') %></a></li>
                <% }); %>
                <li><a data-role="tab" id="tabs-navbar-overview" href="#overview"><%= t.overview %></a></li>
            </ul>
        </div>
        <% products.each(function(type){ %>
            <div id="<%- type.get('MenuTypeid') %>" >
                <ul data-role="listview" data-inset="true">
                    <% type.get('MenuGroup').each(function(group){ %>
                        <li data-role="list-divider"><%- group.get('Name') %></li>
                        <% group.get('Menu').each(function(menu){ %>
                            <% if(menu.get('Availability') == ORDER_AVAILABILITY_OUT_OF_ORDER) { %>
                                <li><a style="color: red"><%- menu.get('Name') %><span class="ui-li-count"><%- parseFloat(menu.get('Price')).toFixed(2) %> <%= i18n.currency %></span></a></li>
                            <% } else { %>
                                <li><a data-menuid="<%- menu.get('Menuid') %>" class='menu-item' <% if(menu.get('Availability') == ORDER_AVAILABILITY_DELAYED) { %> style="color: orange" <% } %> ><%- menu.get('Name') %><span class="ui-li-count"><%- parseFloat(menu.get('Price')).toFixed(2) %> <%= i18n.currency %></span></a></li>
                            <% } %>
                        <% }); %>
                    <% }); %>
                </ul>
            </div>
        <% }); %>
        <div id="overview">
            <a href="#panel-special" data-role="button" data-icon="action" data-mini="true"><%= t.addSpecialOrder %></a>
            <ul data-role="listview" data-inset="true" id="selected">
            </ul>
            <% if(mode == 'new') { %>
                <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.sum %></h3>
                <div class="ui-body ui-body-a ui-corner-all">
                        <h1 style="margin: 0; padding: 0" id='total'>0,00<%= i18n.currency %></h1>
                </div>
            <% } else if(mode == 'edit') { %>
                <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.oldSum %></h3>
                <div class="ui-body ui-body-a ui-corner-all">
                    <h1 style="margin: 0; padding: 0" id='total-old'>0,00<%= i18n.currency %></h1>
                </div>
                <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.newSum %></h3>
                <div class="ui-body ui-body-a ui-corner-all">
                    <h1 style="margin: 0; padding: 0" id='total-new'>0,00<%= i18n.currency %></h1>
                    <%= t.difference %>: <span id="total-difference">0,00 <%= i18n.currency %></span>
                </div>
            <% } %>
        </div>
    </div>
</div>
<div data-role="panel" data-display="overlay" id="panel-order">
</div>
<div data-role="panel" data-display="overlay" id="panel-special">
    <h3 class="ui-bar ui-bar-a ui-corner-all" style="margin: 0;"><%= t.addSpecialOrder %></h3>
    <div class="ui-body ui-body-a ui-corner-all">
        <fieldset data-role="controlgroup" data-mini="true">
            <legend><%= t.extras %>:</legend>
            <textarea cols="40" rows="2" name="panel-special-extra" id="panel-special-extra"></textarea>
        </fieldset>

        <a id="panel-special-add" class="ui-shadow ui-btn ui-mini ui-corner-all ui-icon-plus ui-btn-icon-right"><%= t.add %></a>
        <a data-rel="close" class="ui-shadow ui-btn ui-mini ui-corner-all ui-icon-back ui-btn-icon-right"><%= t.cancel %></a>
    </div>
</div>
<div data-role="footer" data-theme="b" data-position="fixed" >
    <a id="footer-back" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-left ui-icon-carat-l"><%= t.back %></a>
    <a id="footer-finish" class="ui-btn ui-corner-all ui-btn-inline ui-mini ui-btn-icon-right ui-icon-check" style="float:right">
        <% if(mode == 'new') { %>
            <%= t.order %>
        <% } else { %>
            <%= t.change %>
        <% } %>
    </a>
</div>
<div data-role="popup" id="verify-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <% if(mode == 'new') { %>
            <h1><%= t.orderFinished %></h1>
        <% } else { %>
            <h1><%= t.changeFinished %></h1>
        <% } %>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title"><%= t.orderFinishedVerifyText %>/h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.cancel %></a>
        <a id='finished' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>