<div data-role="content">
    <div class="nav-header"><%= header %></div>
    <div>
        <ul data-role="listview" data-inset="true" id="order-modify-price-list">

        </ul>
    </div>
    <div class="ui-body ui-body-a ui-corner-all">
        <input type="button" id="order-modify-price-submit" value="Speichern">
    </div>
</div>
<div data-role="popup" id="order-modify-price-dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false">
    <div data-role="header" data-theme="a">
        <h1>Einzelpreis bearbeiten</h1>
    </div>
    <div role="main" class="ui-content">
        <label for="order-modify-price-dialog-input">Einzelpreis:</label>
        <input type="number" id="order-modify-price-dialog-input"  />

        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back">Abbrechen</a>
        <a id='order-modify-price-dialog-continue' class="ui-btn ui-corner-all ui-shadow ui-btn-b">Fortfahren</a>
    </div>
</div>
<div data-role="popup" data-overlay-theme="b" data-theme="b" data-position-to="window" id="order-modify-price-success-popup" class="ui-content">
    <h3>Änderung erfolgreich!</h3>
</div>