<div class="ui-grid-a">
    <div class="ui-block-a">
        <h2 style="white-space: normal;"><%- name %></h2>
        <p><strong style="white-space: normal;"><%- extras %></strong></p>
    </div>
    <div class="ui-block-b" style="top: 1em; right: 0em; text-align: right; font-size: .75em; font-weight: 400; margin: .6em 0;">
        <% if(mode == 'pay') { %>
	        <%= t.inInvoice %>: <strong><%- amount %></strong>
	        <br/>
	        <%= t.open %>: <strong><%- open %></strong>
	        <br/>
        <% } else { %>
	        <%= t.amount %>: <strong><%- amount %></strong>
	        <br/>
        <% } %>

        <% if(isSpecialOrder == true) { %>
            <strong><%= t.managerNeedsToSetPrice %></strong>
        <% } else { %>
            <%= t.singlePrice %>: <strong><%- parseFloat(price).toFixed(2) %><%= i18n.currency %></strong>
            <br/>
            <%= t.total %>: <strong><%- parseFloat(totalPrice).toFixed(2) %><%= i18n.currency %></strong>
        <% } %>
        <% if(typeof edit !== "undefined") { %>
            <br/>
            <a data-menu-typeid="<%- menuTypeid %>" data-index="<%- index %>" class="order-item-edit ui-btn ui-btn-inline ui-icon-edit ui-btn-icon-left ui-mini"><%= t.edit %></a>
        <% } %>
        <% if(!skipCounts) { %>
            <br/>
            <a data-menu-typeid="<%- menuTypeid %>" data-index="<%- index %>" class="order-item-up ui-btn ui-btn-inline ui-icon-plus ui-btn-icon-notext"><%= t.up %></a>
            <a data-menu-typeid="<%- menuTypeid %>" data-index="<%- index %>" class="order-item-down ui-btn ui-btn-inline ui-icon-minus ui-btn-icon-notext"><%= t.down %></a>
        <% } %>
    </div>
</div>
<% if(typeof statusInformation !== 'undefined') { %>
    <div class="ui-grid-solo">
        <div class="ui-block-a">
            <% if(status == ORDER_STATUS_WAITING) { %>
                <p><%= t.queuePosition %> <%- rank %></p>
            <% } else if(status == ORDER_STATUS_IN_PROGRESS) { %>
                <p style="color:orange;">
                    <%= t.inProgressSince %>
                    <%- $.format.date(MyPOS.DateFromMysql(in_progress_begin), DATE_JS_TIMEFORMAT) %>
                    <%= t.position %> <%- rank %>
                </p>
                <p><%= t.editor %>: <%- handled_by_name %></p>
                <p><%= t.recieved %>: <%- amount_recieved_total %></p>
                <p><%= t.deliveries %>:</p>
                <ul class="ui-mini">
                    <% _.each(amount_recieved, function(current_amount, current_date){ %>
                        <li><%- $.format.date(MyPOS.DateFromMysql(current_date), DATE_JS_TIMEFORMAT) %>: <%- current_amount %></li>
                    <% }) %>
                </ul>
            <% } else if(status == ORDER_STATUS_FINISHED) { %>
                <p style="color:green;">
                        <%= t.doneEditFrom %>
                        <%- $.format.date(MyPOS.DateFromMysql(in_progress_begin), DATE_JS_TIMEFORMAT) %>
                        <%= t.doneEditTo %>
                        <%- $.format.date(MyPOS.DateFromMysql(in_progress_done), DATE_JS_TIMEFORMAT) %>
                </p>
                <p><%= t.editor %>: <%- handled_by_name %></p>
                <p><%= t.recieved %>: <%- amount_recieved_total %></p>
                <p><%= t.deliveries %>:</p>
                <ul class="ui-mini">
                    <% _.each(amount_recieved, function(current_amount, current_date){ %>
                        <li><%- $.format.date(MyPOS.DateFromMysql(current_date), DATE_JS_TIMEFORMAT) %>: <%- current_amount %></li>
                    <% }) %>
                </ul>
            <% } %>
        </div>
    </div>
<% } %>
