<div data-role="content">
    <div class="nav-header"></div>
    <div data-role="popup" data-overlay-theme="b" data-theme="b" data-position-to="window" id="success-popup" class="ui-content">
         <h3><%= t.paymentSuccessfull %></h3>
    </div>
    <div data-role="popup" data-position-to="window" id="add-coupon-popup" data-overlay-theme="b" data-theme="b">
         <div data-role="header">
            <h1><%= t.addCoupon %></h1>
        </div>
        <div role="main" class="ui-content">
            <label for="coupon-code"><%= t.code %></label>
            <input type="text" id="coupon-code" />

            <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
            <a id='coupon-code-verify' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.verify %></a>
        </div>
    </div>
    <div data-role="navbar">
        <ul>
            <li><a id="show-all" class="ui-btn-active ui-mini"><%= t.openOnTable %></a></li>
            <li><a id="show-single" class="ui-mini"><%= t.openOffOrder %></a></li>
        </ul>
    </div>
    <div>
        <a class="ui-btn ui-mini" id='button-all'><%= t.payAll %></a>
    </div>
    <div>
        <ul data-role="listview" data-inset="true" id="open-orders-list"></ul>
    </div>
    <div>
        <h3 class="ui-bar ui-bar-a ui-corner-all"><%= t.sumForInvoice %></h3>
        <div class="ui-body ui-body-a ui-corner-all">
            <h1 style="margin: 0; padding: 0" id="invoice-price">0.00 <%= i18n.currency %></h1>
            <div id="invoice-price-without-coupon"></div>
        </div>
    </div>
    <div class="ui-body ui-body-a ui-corner-all">
        <form>
            <fieldset data-role="controlgroup" data-mini="true">
                <input type="button" id="use-coupon" value="<%= t.addCoupon %>">
                <ul data-role="listview" data-inset="true" id="coupons-list"></ul>
            </fieldset>
            <fieldset data-role="controlgroup" data-mini="true">
                <input type="checkbox" name="print" id="print">
                <label for="print"><%= t.printReceipt %></label>
                <select name="checkbox-printer" id="printer">
                    <% printers.each(function(printer){ %>
                        <option value="<%- printer.get('EventPrinterid') %>"><%= t.printer %>: <%- printer.get('Name') %></option>
                    <% }) %>
                </select>
            </fieldset>
            <fieldset data-role="controlgroup" data-mini="true">
                <input type="checkbox" name="continue" id="continue" checked="true">
                <label for="continue"><%= t.stayOnPage %></label>
            </fieldset>

            <input type="button" id="submit" value="<%= t.payed %>">
        </form>
    </div>
</div>