 <div data-role="content">
    <div class="nav-header"></div>
    <div data-role="controlgroup" data-type="horizontal" data-mini="true">
        <input type="text" id="filterTable-input" data-type="search" data-wrapper-class="controlgroup-textinput-mini ui-btn" style="width: 100px !important">
        <button id='search-btn'><%= t.advancedSearch %></button>
    </div>
    <table data-role="table"  data-filter="true" data-input="#filterTable-input"  id="table" class="ui-responsive table-stroke table-stripe">
        <thead>
            <tr>
                <th><%= t.table %></th>
                <th><%= t.sum %></th>
                <th><%= t.status %></th>
                <th><%= t.options %></th>
            </tr>
        </thead>
        <tbody>
            <% orders.each(function(order){ %>
                <tr>
                    <th><%- order.get('EventTable').get('Name') %></th>
                    <td><%- parseFloat(order.get('price')).toFixed(2) %> <%= i18n.currency %></td>
                    <td>
                        <%
                            if(order.get('OrderInProgresses').length == 0) {
                                print(t.waiting);
                            } else if(order.get('Finished') == null) {
                                print(t.inProgress);
                            } else {
                                print(t.finished);
                            }
                        %>
                        -
                        <% if(order.get('InvoiceFinished')) { %>
                            <span style="color: green;"><%= t.billed %></span>
                        <% } else { %>
                            <span style="color: red;"><%= t.unbilled %></span>
                        <% } %>
                    </td>
                    <td>
                        <a data-order-id="<%- order.get('Orderid') %>" class="info-btn ui-btn ui-icon-info ui-mini ui-btn-icon-left"><%= t.info %></a>
                        <% if (!order.get('InvoiceFinished')) { %>
                           <a data-order-id="<%- order.get('Orderid') %>" data-table-nr="<%- order.get('EventTable').get('Name') %>" class="pay-btn ui-btn ui-icon-shop ui-mini ui-btn-icon-left"><%= t.createInvoice %></a>
                        <% } %>
                        <% if (order.get('OrderInProgresses').length == 0) { %>
                           <a data-order-id="<%- order.get('Orderid') %>" data-table-nr="<%- order.get('EventTable').get('Name') %>"  class="modify-btn ui-btn ui-icon-edit ui-mini ui-btn-icon-left"><%= t.edit %></a>
                           <a data-order-id="<%- order.get('Orderid') %>" class="cancel-btn ui-btn ui-icon-delete ui-mini ui-btn-icon-left" data-rel="popup" data-position-to="window"><%= t.cancel %></a>
                        <% } %>
                        <% if (userRoles & USER_ROLE_ORDER_MODIFY_PRIORITY && order.get('OrderInProgresses').length == 0) { %>
                            <a data-order-id="<%- order.get('Orderid') %>" class="manage-priority-btn ui-btn ui-icon-alert ui-mini ui-btn-icon-left" data-rel="popup" data-position-to="window"><%= t.priority %></a>
                        <% } %>
                        <% if (userRoles & USER_ROLE_ORDER_MODIFY_PRICE) { %>
                            <a data-order-id="<%- order.get('Orderid') %>" class="manage-price-btn ui-btn ui-icon-star ui-mini ui-btn-icon-left" data-rel="popup" data-position-to="window"><%= t.editPrice %></a>
                        <% } %>
                    </td>
                </tr>
            <% }); %>
        </tbody>
    </table>
</div>
<div data-role="popup" id="dialog" data-overlay-theme="b" data-theme="b" data-dismissible="false" style="max-width:400px;">
    <div data-role="header" data-theme="a">
        <h1 id="dialog-title"></h1>
    </div>
    <div role="main" class="ui-content">
        <h3 class="ui-title" id="dialog-text"></h3>
        <a class="ui-btn ui-corner-all ui-shadow ui-btn-b" data-rel="back"><%= t.abort %></a>
        <a id='dialog-continue' class="ui-btn ui-corner-all ui-shadow ui-btn-b"><%= t.continue %></a>
    </div>
</div>
<div data-role="popup" data-overlay-theme="b" data-theme="b" data-position-to="window" id="cancel-success-popup" class="ui-content">
    <h3><%= t.cancellationSuccessful %>!</h3>
</div>